// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAgent = `-- name: GetAgent :one
SELECT agent_id, public_key, discovery_url, requester_type, registered_at, billing_ref FROM ramp.agents WHERE agent_id = $1
`

func (q *Queries) GetAgent(ctx context.Context, agentID string) (RampAgent, error) {
	row := q.db.QueryRow(ctx, getAgent, agentID)
	var i RampAgent
	err := row.Scan(
		&i.AgentID,
		&i.PublicKey,
		&i.DiscoveryUrl,
		&i.RequesterType,
		&i.RegisteredAt,
		&i.BillingRef,
	)
	return i, err
}

const setAgentBillingRef = `-- name: SetAgentBillingRef :one
UPDATE ramp.agents
   SET billing_ref = $2
 WHERE agent_id = $1
   AND billing_ref IS NULL
RETURNING agent_id, public_key, discovery_url, requester_type, registered_at, billing_ref
`

type SetAgentBillingRefParams struct {
	AgentID    string      `json:"agent_id"`
	BillingRef pgtype.Text `json:"billing_ref"`
}

// Stores the billing account id for an agent, first write wins. The
// billing_ref IS NULL guard makes a repeat call a no-op (zero rows →
// pgx.ErrNoRows), so a stored ref is never overwritten (ADR-021 D4). The
// column is deliberately absent from UpsertAgent's update list: a key
// rotation re-upsert must leave billing_ref intact (ADR-021 D3).
func (q *Queries) SetAgentBillingRef(ctx context.Context, arg SetAgentBillingRefParams) (RampAgent, error) {
	row := q.db.QueryRow(ctx, setAgentBillingRef, arg.AgentID, arg.BillingRef)
	var i RampAgent
	err := row.Scan(
		&i.AgentID,
		&i.PublicKey,
		&i.DiscoveryUrl,
		&i.RequesterType,
		&i.RegisteredAt,
		&i.BillingRef,
	)
	return i, err
}

const upsertAgent = `-- name: UpsertAgent :one
INSERT INTO ramp.agents (agent_id, public_key, discovery_url, requester_type)
VALUES ($1, $2, $3, $4)
ON CONFLICT (agent_id) DO UPDATE
    SET public_key = EXCLUDED.public_key,
        discovery_url = EXCLUDED.discovery_url,
        requester_type = EXCLUDED.requester_type
RETURNING agent_id, public_key, discovery_url, requester_type, registered_at, billing_ref
`

type UpsertAgentParams struct {
	AgentID       string            `json:"agent_id"`
	PublicKey     []byte            `json:"public_key"`
	DiscoveryUrl  pgtype.Text       `json:"discovery_url"`
	RequesterType RampRequesterType `json:"requester_type"`
}

func (q *Queries) UpsertAgent(ctx context.Context, arg UpsertAgentParams) (RampAgent, error) {
	row := q.db.QueryRow(ctx, upsertAgent,
		arg.AgentID,
		arg.PublicKey,
		arg.DiscoveryUrl,
		arg.RequesterType,
	)
	var i RampAgent
	err := row.Scan(
		&i.AgentID,
		&i.PublicKey,
		&i.DiscoveryUrl,
		&i.RequesterType,
		&i.RegisteredAt,
		&i.BillingRef,
	)
	return i, err
}
