// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAgent = `-- name: GetAgent :one
SELECT agent_id, public_key, manifest_url, requester_type, registered_at FROM ramp.agents WHERE agent_id = $1
`

func (q *Queries) GetAgent(ctx context.Context, agentID string) (RampAgent, error) {
	row := q.db.QueryRow(ctx, getAgent, agentID)
	var i RampAgent
	err := row.Scan(
		&i.AgentID,
		&i.PublicKey,
		&i.ManifestUrl,
		&i.RequesterType,
		&i.RegisteredAt,
	)
	return i, err
}

const upsertAgent = `-- name: UpsertAgent :one
INSERT INTO ramp.agents (agent_id, public_key, manifest_url, requester_type)
VALUES ($1, $2, $3, $4)
ON CONFLICT (agent_id) DO UPDATE
    SET public_key = EXCLUDED.public_key,
        manifest_url = EXCLUDED.manifest_url,
        requester_type = EXCLUDED.requester_type
RETURNING agent_id, public_key, manifest_url, requester_type, registered_at
`

type UpsertAgentParams struct {
	AgentID       string            `json:"agent_id"`
	PublicKey     []byte            `json:"public_key"`
	ManifestUrl   pgtype.Text       `json:"manifest_url"`
	RequesterType RampRequesterType `json:"requester_type"`
}

func (q *Queries) UpsertAgent(ctx context.Context, arg UpsertAgentParams) (RampAgent, error) {
	row := q.db.QueryRow(ctx, upsertAgent,
		arg.AgentID,
		arg.PublicKey,
		arg.ManifestUrl,
		arg.RequesterType,
	)
	var i RampAgent
	err := row.Scan(
		&i.AgentID,
		&i.PublicKey,
		&i.ManifestUrl,
		&i.RequesterType,
		&i.RegisteredAt,
	)
	return i, err
}
