// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendAuditLog = `-- name: AppendAuditLog :exec
INSERT INTO ramp.audit_log (
    log_id, actor, source_addr, action, detail, tenant_id, request_id
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type AppendAuditLogParams struct {
	LogID      string      `json:"log_id"`
	Actor      pgtype.Text `json:"actor"`
	SourceAddr string      `json:"source_addr"`
	Action     string      `json:"action"`
	Detail     []byte      `json:"detail"`
	TenantID   string      `json:"tenant_id"`
	RequestID  pgtype.Text `json:"request_id"`
}

// Appends one admin control-plane change to the append-only audit log. Written
// inside the setter's transaction, after the rows-affected check, so an
// unknown-tenant no-op leaves no row.
func (q *Queries) AppendAuditLog(ctx context.Context, arg AppendAuditLogParams) error {
	_, err := q.db.Exec(ctx, appendAuditLog,
		arg.LogID,
		arg.Actor,
		arg.SourceAddr,
		arg.Action,
		arg.Detail,
		arg.TenantID,
		arg.RequestID,
	)
	return err
}

const auditLogByTenant = `-- name: AuditLogByTenant :many
SELECT log_id, actor, source_addr, action, detail, tenant_id, request_id, created_at FROM ramp.audit_log
 WHERE tenant_id = $1
 ORDER BY created_at DESC
`

// Returns the audit trail for a tenant, most recent first. Read path for admin
// change reconstruction and the integration tests' side-effect assertions.
func (q *Queries) AuditLogByTenant(ctx context.Context, tenantID string) ([]RampAuditLog, error) {
	rows, err := q.db.Query(ctx, auditLogByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RampAuditLog{}
	for rows.Next() {
		var i RampAuditLog
		if err := rows.Scan(
			&i.LogID,
			&i.Actor,
			&i.SourceAddr,
			&i.Action,
			&i.Detail,
			&i.TenantID,
			&i.RequestID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
