// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package sqlc

import (
	"context"
)

const getCatalogEntry = `-- name: GetCatalogEntry :one
SELECT resource_id, tenant_id, uri, uri_prefix, pricing, licensing_rules, delivery_method, created_at, updated_at FROM ramp.catalog WHERE resource_id = $1
`

func (q *Queries) GetCatalogEntry(ctx context.Context, resourceID string) (RampCatalog, error) {
	row := q.db.QueryRow(ctx, getCatalogEntry, resourceID)
	var i RampCatalog
	err := row.Scan(
		&i.ResourceID,
		&i.TenantID,
		&i.Uri,
		&i.UriPrefix,
		&i.Pricing,
		&i.LicensingRules,
		&i.DeliveryMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCatalogEntry = `-- name: InsertCatalogEntry :one
INSERT INTO ramp.catalog (
    resource_id, tenant_id, uri, uri_prefix, pricing, licensing_rules,
    delivery_method
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING resource_id, tenant_id, uri, uri_prefix, pricing, licensing_rules, delivery_method, created_at, updated_at
`

type InsertCatalogEntryParams struct {
	ResourceID     string             `json:"resource_id"`
	TenantID       string             `json:"tenant_id"`
	Uri            string             `json:"uri"`
	UriPrefix      string             `json:"uri_prefix"`
	Pricing        []byte             `json:"pricing"`
	LicensingRules []byte             `json:"licensing_rules"`
	DeliveryMethod RampDeliveryMethod `json:"delivery_method"`
}

func (q *Queries) InsertCatalogEntry(ctx context.Context, arg InsertCatalogEntryParams) (RampCatalog, error) {
	row := q.db.QueryRow(ctx, insertCatalogEntry,
		arg.ResourceID,
		arg.TenantID,
		arg.Uri,
		arg.UriPrefix,
		arg.Pricing,
		arg.LicensingRules,
		arg.DeliveryMethod,
	)
	var i RampCatalog
	err := row.Scan(
		&i.ResourceID,
		&i.TenantID,
		&i.Uri,
		&i.UriPrefix,
		&i.Pricing,
		&i.LicensingRules,
		&i.DeliveryMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllCatalog = `-- name: ListAllCatalog :many
SELECT resource_id, tenant_id, uri, uri_prefix, pricing, licensing_rules, delivery_method, created_at, updated_at FROM ramp.catalog ORDER BY tenant_id, uri_prefix
`

func (q *Queries) ListAllCatalog(ctx context.Context) ([]RampCatalog, error) {
	rows, err := q.db.Query(ctx, listAllCatalog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RampCatalog{}
	for rows.Next() {
		var i RampCatalog
		if err := rows.Scan(
			&i.ResourceID,
			&i.TenantID,
			&i.Uri,
			&i.UriPrefix,
			&i.Pricing,
			&i.LicensingRules,
			&i.DeliveryMethod,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogByTenant = `-- name: ListCatalogByTenant :many
SELECT resource_id, tenant_id, uri, uri_prefix, pricing, licensing_rules, delivery_method, created_at, updated_at FROM ramp.catalog WHERE tenant_id = $1 ORDER BY uri_prefix
`

func (q *Queries) ListCatalogByTenant(ctx context.Context, tenantID string) ([]RampCatalog, error) {
	rows, err := q.db.Query(ctx, listCatalogByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RampCatalog{}
	for rows.Next() {
		var i RampCatalog
		if err := rows.Scan(
			&i.ResourceID,
			&i.TenantID,
			&i.Uri,
			&i.UriPrefix,
			&i.Pricing,
			&i.LicensingRules,
			&i.DeliveryMethod,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCatalogEntry = `-- name: UpsertCatalogEntry :one
INSERT INTO ramp.catalog (
    resource_id, tenant_id, uri, uri_prefix, pricing, licensing_rules,
    delivery_method
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (resource_id) DO UPDATE
   SET tenant_id = EXCLUDED.tenant_id,
       uri = EXCLUDED.uri,
       uri_prefix = EXCLUDED.uri_prefix,
       pricing = EXCLUDED.pricing,
       licensing_rules = EXCLUDED.licensing_rules,
       delivery_method = EXCLUDED.delivery_method,
       updated_at = NOW()
RETURNING resource_id, tenant_id, uri, uri_prefix, pricing, licensing_rules, delivery_method, created_at, updated_at
`

type UpsertCatalogEntryParams struct {
	ResourceID     string             `json:"resource_id"`
	TenantID       string             `json:"tenant_id"`
	Uri            string             `json:"uri"`
	UriPrefix      string             `json:"uri_prefix"`
	Pricing        []byte             `json:"pricing"`
	LicensingRules []byte             `json:"licensing_rules"`
	DeliveryMethod RampDeliveryMethod `json:"delivery_method"`
}

func (q *Queries) UpsertCatalogEntry(ctx context.Context, arg UpsertCatalogEntryParams) (RampCatalog, error) {
	row := q.db.QueryRow(ctx, upsertCatalogEntry,
		arg.ResourceID,
		arg.TenantID,
		arg.Uri,
		arg.UriPrefix,
		arg.Pricing,
		arg.LicensingRules,
		arg.DeliveryMethod,
	)
	var i RampCatalog
	err := row.Scan(
		&i.ResourceID,
		&i.TenantID,
		&i.Uri,
		&i.UriPrefix,
		&i.Pricing,
		&i.LicensingRules,
		&i.DeliveryMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
