// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type RampDeliveryMethod string

const (
	RampDeliveryMethodDIRECT       RampDeliveryMethod = "DIRECT"
	RampDeliveryMethodINSTRUCTIONS RampDeliveryMethod = "INSTRUCTIONS"
	RampDeliveryMethodSTREAMING    RampDeliveryMethod = "STREAMING"
)

func (e *RampDeliveryMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RampDeliveryMethod(s)
	case string:
		*e = RampDeliveryMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for RampDeliveryMethod: %T", src)
	}
	return nil
}

type NullRampDeliveryMethod struct {
	RampDeliveryMethod RampDeliveryMethod `json:"ramp_delivery_method"`
	Valid              bool               `json:"valid"` // Valid is true if RampDeliveryMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRampDeliveryMethod) Scan(value interface{}) error {
	if value == nil {
		ns.RampDeliveryMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RampDeliveryMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRampDeliveryMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RampDeliveryMethod), nil
}

func (e RampDeliveryMethod) Valid() bool {
	switch e {
	case RampDeliveryMethodDIRECT,
		RampDeliveryMethodINSTRUCTIONS,
		RampDeliveryMethodSTREAMING:
		return true
	}
	return false
}

type RampDenialReason string

const (
	RampDenialReasonBILLINGREFINACTIVE      RampDenialReason = "BILLING_REF_INACTIVE"
	RampDenialReasonINSUFFICIENTBALANCE     RampDenialReason = "INSUFFICIENT_BALANCE"
	RampDenialReasonRATELIMITED             RampDenialReason = "RATE_LIMITED"
	RampDenialReasonCONTENTUNAVAILABLE      RampDenialReason = "CONTENT_UNAVAILABLE"
	RampDenialReasonRESTRICTIONNOTSATISFIED RampDenialReason = "RESTRICTION_NOT_SATISFIED"
	RampDenialReasonREPORTINGOVERDUE        RampDenialReason = "REPORTING_OVERDUE"
	RampDenialReasonOFFEREXPIRED            RampDenialReason = "OFFER_EXPIRED"
	RampDenialReasonSIGNATUREINVALID        RampDenialReason = "SIGNATURE_INVALID"
	RampDenialReasonQUOTAEXCEEDED           RampDenialReason = "QUOTA_EXCEEDED"
	RampDenialReasonDELEGATIONINVALID       RampDenialReason = "DELEGATION_INVALID"
	RampDenialReasonSCOPEINSUFFICIENT       RampDenialReason = "SCOPE_INSUFFICIENT"
	RampDenialReasonENTITLEMENTMISSING      RampDenialReason = "ENTITLEMENT_MISSING"
	RampDenialReasonENTITLEMENTMALFORMED    RampDenialReason = "ENTITLEMENT_MALFORMED"
	RampDenialReasonENTITLEMENTEXPIRED      RampDenialReason = "ENTITLEMENT_EXPIRED"
	RampDenialReasonENTITLEMENTWRONGBUYER   RampDenialReason = "ENTITLEMENT_WRONG_BUYER"
	RampDenialReasonSUBSCRIPTIONLAPSED      RampDenialReason = "SUBSCRIPTION_LAPSED"
	RampDenialReasonENTITLEMENTNOTGRANTED   RampDenialReason = "ENTITLEMENT_NOT_GRANTED"
)

func (e *RampDenialReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RampDenialReason(s)
	case string:
		*e = RampDenialReason(s)
	default:
		return fmt.Errorf("unsupported scan type for RampDenialReason: %T", src)
	}
	return nil
}

type NullRampDenialReason struct {
	RampDenialReason RampDenialReason `json:"ramp_denial_reason"`
	Valid            bool             `json:"valid"` // Valid is true if RampDenialReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRampDenialReason) Scan(value interface{}) error {
	if value == nil {
		ns.RampDenialReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RampDenialReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRampDenialReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RampDenialReason), nil
}

func (e RampDenialReason) Valid() bool {
	switch e {
	case RampDenialReasonBILLINGREFINACTIVE,
		RampDenialReasonINSUFFICIENTBALANCE,
		RampDenialReasonRATELIMITED,
		RampDenialReasonCONTENTUNAVAILABLE,
		RampDenialReasonRESTRICTIONNOTSATISFIED,
		RampDenialReasonREPORTINGOVERDUE,
		RampDenialReasonOFFEREXPIRED,
		RampDenialReasonSIGNATUREINVALID,
		RampDenialReasonQUOTAEXCEEDED,
		RampDenialReasonDELEGATIONINVALID,
		RampDenialReasonSCOPEINSUFFICIENT,
		RampDenialReasonENTITLEMENTMISSING,
		RampDenialReasonENTITLEMENTMALFORMED,
		RampDenialReasonENTITLEMENTEXPIRED,
		RampDenialReasonENTITLEMENTWRONGBUYER,
		RampDenialReasonSUBSCRIPTIONLAPSED,
		RampDenialReasonENTITLEMENTNOTGRANTED:
		return true
	}
	return false
}

type RampObligationState string

const (
	RampObligationStatePENDING    RampObligationState = "PENDING"
	RampObligationStateRECEIVED   RampObligationState = "RECEIVED"
	RampObligationStateACCEPTED   RampObligationState = "ACCEPTED"
	RampObligationStateCHALLENGED RampObligationState = "CHALLENGED"
	RampObligationStateEXPIRED    RampObligationState = "EXPIRED"
)

func (e *RampObligationState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RampObligationState(s)
	case string:
		*e = RampObligationState(s)
	default:
		return fmt.Errorf("unsupported scan type for RampObligationState: %T", src)
	}
	return nil
}

type NullRampObligationState struct {
	RampObligationState RampObligationState `json:"ramp_obligation_state"`
	Valid               bool                `json:"valid"` // Valid is true if RampObligationState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRampObligationState) Scan(value interface{}) error {
	if value == nil {
		ns.RampObligationState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RampObligationState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRampObligationState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RampObligationState), nil
}

func (e RampObligationState) Valid() bool {
	switch e {
	case RampObligationStatePENDING,
		RampObligationStateRECEIVED,
		RampObligationStateACCEPTED,
		RampObligationStateCHALLENGED,
		RampObligationStateEXPIRED:
		return true
	}
	return false
}

type RampRequesterType string

const (
	RampRequesterTypeAGENT     RampRequesterType = "AGENT"
	RampRequesterTypeHUMANTOOL RampRequesterType = "HUMAN_TOOL"
	RampRequesterTypeSERVICE   RampRequesterType = "SERVICE"
	RampRequesterTypeDELEGATED RampRequesterType = "DELEGATED"
	RampRequesterTypeRESEARCH  RampRequesterType = "RESEARCH"
	RampRequesterTypeBROKER    RampRequesterType = "BROKER"
)

func (e *RampRequesterType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RampRequesterType(s)
	case string:
		*e = RampRequesterType(s)
	default:
		return fmt.Errorf("unsupported scan type for RampRequesterType: %T", src)
	}
	return nil
}

type NullRampRequesterType struct {
	RampRequesterType RampRequesterType `json:"ramp_requester_type"`
	Valid             bool              `json:"valid"` // Valid is true if RampRequesterType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRampRequesterType) Scan(value interface{}) error {
	if value == nil {
		ns.RampRequesterType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RampRequesterType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRampRequesterType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RampRequesterType), nil
}

func (e RampRequesterType) Valid() bool {
	switch e {
	case RampRequesterTypeAGENT,
		RampRequesterTypeHUMANTOOL,
		RampRequesterTypeSERVICE,
		RampRequesterTypeDELEGATED,
		RampRequesterTypeRESEARCH,
		RampRequesterTypeBROKER:
		return true
	}
	return false
}

type RampSigningScheme string

const (
	RampSigningSchemeED25519          RampSigningScheme = "ED25519"
	RampSigningSchemeAWSCLOUDFRONTRSA RampSigningScheme = "AWS_CLOUDFRONT_RSA"
)

func (e *RampSigningScheme) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RampSigningScheme(s)
	case string:
		*e = RampSigningScheme(s)
	default:
		return fmt.Errorf("unsupported scan type for RampSigningScheme: %T", src)
	}
	return nil
}

type NullRampSigningScheme struct {
	RampSigningScheme RampSigningScheme `json:"ramp_signing_scheme"`
	Valid             bool              `json:"valid"` // Valid is true if RampSigningScheme is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRampSigningScheme) Scan(value interface{}) error {
	if value == nil {
		ns.RampSigningScheme, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RampSigningScheme.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRampSigningScheme) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RampSigningScheme), nil
}

func (e RampSigningScheme) Valid() bool {
	switch e {
	case RampSigningSchemeED25519,
		RampSigningSchemeAWSCLOUDFRONTRSA:
		return true
	}
	return false
}

type RampValidationOutcome string

const (
	RampValidationOutcomeVALIDATED         RampValidationOutcome = "VALIDATED"
	RampValidationOutcomeREJECTEDFIELDS    RampValidationOutcome = "REJECTED_FIELDS"
	RampValidationOutcomeREJECTEDWINDOW    RampValidationOutcome = "REJECTED_WINDOW"
	RampValidationOutcomeREJECTEDTOLERANCE RampValidationOutcome = "REJECTED_TOLERANCE"
	RampValidationOutcomeREJECTEDBILLINGID RampValidationOutcome = "REJECTED_BILLING_ID"
	RampValidationOutcomeREJECTEDTIMESTAMP RampValidationOutcome = "REJECTED_TIMESTAMP"
	RampValidationOutcomeREJECTEDEXCHANGE  RampValidationOutcome = "REJECTED_EXCHANGE"
)

func (e *RampValidationOutcome) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RampValidationOutcome(s)
	case string:
		*e = RampValidationOutcome(s)
	default:
		return fmt.Errorf("unsupported scan type for RampValidationOutcome: %T", src)
	}
	return nil
}

type NullRampValidationOutcome struct {
	RampValidationOutcome RampValidationOutcome `json:"ramp_validation_outcome"`
	Valid                 bool                  `json:"valid"` // Valid is true if RampValidationOutcome is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRampValidationOutcome) Scan(value interface{}) error {
	if value == nil {
		ns.RampValidationOutcome, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RampValidationOutcome.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRampValidationOutcome) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RampValidationOutcome), nil
}

func (e RampValidationOutcome) Valid() bool {
	switch e {
	case RampValidationOutcomeVALIDATED,
		RampValidationOutcomeREJECTEDFIELDS,
		RampValidationOutcomeREJECTEDWINDOW,
		RampValidationOutcomeREJECTEDTOLERANCE,
		RampValidationOutcomeREJECTEDBILLINGID,
		RampValidationOutcomeREJECTEDTIMESTAMP,
		RampValidationOutcomeREJECTEDEXCHANGE:
		return true
	}
	return false
}

type RampAgent struct {
	AgentID       string             `json:"agent_id"`
	PublicKey     []byte             `json:"public_key"`
	DiscoveryUrl  pgtype.Text        `json:"discovery_url"`
	RequesterType RampRequesterType  `json:"requester_type"`
	RegisteredAt  pgtype.Timestamptz `json:"registered_at"`
	BillingRef    pgtype.Text        `json:"billing_ref"`
}

type RampAuditLog struct {
	LogID      string             `json:"log_id"`
	Actor      pgtype.Text        `json:"actor"`
	SourceAddr string             `json:"source_addr"`
	Action     string             `json:"action"`
	Detail     []byte             `json:"detail"`
	TenantID   string             `json:"tenant_id"`
	RequestID  pgtype.Text        `json:"request_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type RampCatalog struct {
	ResourceID      string             `json:"resource_id"`
	TenantID        string             `json:"tenant_id"`
	Uri             string             `json:"uri"`
	UriPrefix       string             `json:"uri_prefix"`
	Pricing         []byte             `json:"pricing"`
	DeliveryMethod  RampDeliveryMethod `json:"delivery_method"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Terms           []byte             `json:"terms"`
	Metadata        []byte             `json:"metadata"`
	ResourceOwnerID string             `json:"resource_owner_id"`
}

type RampReportingObligation struct {
	ObligationID      string                    `json:"obligation_id"`
	TransactionID     string                    `json:"transaction_id"`
	State             RampObligationState       `json:"state"`
	WindowSeconds     pgtype.Int4               `json:"window_seconds"`
	Deadline          pgtype.Timestamptz        `json:"deadline"`
	ConsumedQuantity  pgtype.Numeric            `json:"consumed_quantity"`
	ReceivedAt        pgtype.Timestamptz        `json:"received_at"`
	CreatedAt         pgtype.Timestamptz        `json:"created_at"`
	RequiredFields    []string                  `json:"required_fields"`
	EstimatedQuantity int64                     `json:"estimated_quantity"`
	QuantityTolerance pgtype.Numeric            `json:"quantity_tolerance"`
	ValidationOutcome NullRampValidationOutcome `json:"validation_outcome"`
	ValidatedAt       pgtype.Timestamptz        `json:"validated_at"`
	SourceReportID    pgtype.Text               `json:"source_report_id"`
	IssuedReportID    pgtype.Text               `json:"issued_report_id"`
}

type RampTenant struct {
	TenantID                   string             `json:"tenant_id"`
	Domain                     string             `json:"domain"`
	HmacSecretRef              string             `json:"hmac_secret_ref"`
	Ed25519KeyRef              string             `json:"ed25519_key_ref"`
	ReportingPolicy            []byte             `json:"reporting_policy"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	SigningScheme              RampSigningScheme  `json:"signing_scheme"`
	RsaKeyRef                  pgtype.Text        `json:"rsa_key_ref"`
	CloudfrontKeyPairID        pgtype.Text        `json:"cloudfront_key_pair_id"`
	AllowBrokerRelay           bool               `json:"allow_broker_relay"`
	FeeRateBps                 int32              `json:"fee_rate_bps"`
	FeeRateNotes               pgtype.Text        `json:"fee_rate_notes"`
	ActivateNewAgentsByDefault bool               `json:"activate_new_agents_by_default"`
}

type RampTenantResourceOwnerFee struct {
	TenantID        string             `json:"tenant_id"`
	ResourceOwnerID string             `json:"resource_owner_id"`
	FeeRateBps      int32              `json:"fee_rate_bps"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type RampTransactionEvidence struct {
	TransactionID                     string             `json:"transaction_id"`
	TenantID                          string             `json:"tenant_id"`
	OfferID                           string             `json:"offer_id"`
	OfferJson                         []byte             `json:"offer_json"`
	OfferCanonicalBytes               []byte             `json:"offer_canonical_bytes"`
	OfferSignature                    string             `json:"offer_signature"`
	OfferSignatureAlgorithm           string             `json:"offer_signature_algorithm"`
	ExchangeSigningPublicKey          []byte             `json:"exchange_signing_public_key"`
	AgentAcceptanceSignature          string             `json:"agent_acceptance_signature"`
	AgentAcceptanceCanonicalBytes     []byte             `json:"agent_acceptance_canonical_bytes"`
	AgentAcceptanceSignatureAlgorithm string             `json:"agent_acceptance_signature_algorithm"`
	RequesterID                       string             `json:"requester_id"`
	RequesterDomain                   string             `json:"requester_domain"`
	RequestIdempotencyKey             string             `json:"request_idempotency_key"`
	AgentPublicKey                    []byte             `json:"agent_public_key"`
	AgentDiscoveryUrl                 string             `json:"agent_discovery_url"`
	SignedUrlFull                     string             `json:"signed_url_full"`
	RequestID                         pgtype.Text        `json:"request_id"`
	RequestIDMinted                   pgtype.Bool        `json:"request_id_minted"`
	CreatedAt                         pgtype.Timestamptz `json:"created_at"`
}

type RampTransactionLog struct {
	TransactionID     string               `json:"transaction_id"`
	IdempotencyKey    string               `json:"idempotency_key"`
	TenantID          string               `json:"tenant_id"`
	AgentID           string               `json:"agent_id"`
	ResourceID        string               `json:"resource_id"`
	OfferID           string               `json:"offer_id"`
	AgentIdentityHash []byte               `json:"agent_identity_hash"`
	SignedUrlHash     []byte               `json:"signed_url_hash"`
	Expiry            pgtype.Timestamptz   `json:"expiry"`
	BillingID         pgtype.Text          `json:"billing_id"`
	UnitCost          pgtype.Numeric       `json:"unit_cost"`
	Currency          string               `json:"currency"`
	ConsumedUnit      pgtype.Text          `json:"consumed_unit"`
	DenialReason      NullRampDenialReason `json:"denial_reason"`
	CreatedAt         pgtype.Timestamptz   `json:"created_at"`
	ResultPayload     []byte               `json:"result_payload"`
}
