// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateObligation(ctx context.Context, arg CreateObligationParams) (RampReportingObligation, error)
	// Writes the full transaction row. The handler MUST await this commit before
	// returning the signed URL to the caller (write-before-sign invariant).
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (RampTransactionLog, error)
	// Idempotent-retry probe for ReportUsage: returns the obligation row whose
	// (transaction_id, source_report_id) pair was already recorded. A non-empty
	// hit means the caller is replaying a prior UsageReport and the service must
	// return the original issued_report_id without re-running validation.
	FindObligationBySourceReportID(ctx context.Context, arg FindObligationBySourceReportIDParams) (RampReportingObligation, error)
	GetAgent(ctx context.Context, agentID string) (RampAgent, error)
	GetCatalogEntry(ctx context.Context, resourceID string) (RampCatalog, error)
	GetObligationByTransaction(ctx context.Context, transactionID string) (RampReportingObligation, error)
	// Loads the most-recent obligation for a transaction together with the
	// transaction + tenant fields required for protocol validation AND for the
	// caller-identity / broker-relay authorization checks. Single round-trip
	// for ReportUsage's pre-persist validation; the *ForUpdate variant below
	// locks the obligation row so concurrent reports cannot race the state
	// transition.
	GetObligationWithTransaction(ctx context.Context, transactionID string) (GetObligationWithTransactionRow, error)
	// Same join as GetObligationWithTransaction but locks the obligation row for
	// the duration of the surrounding transaction. ReportUsage uses this inside
	// pgx.BeginFunc so the load/validate/write happens atomically against a held
	// row. The transaction_log + tenants rows are read-only
	// on this path and need no lock.
	GetObligationWithTransactionForUpdate(ctx context.Context, transactionID string) (GetObligationWithTransactionForUpdateRow, error)
	GetTenantByDomain(ctx context.Context, domain string) (RampTenant, error)
	GetTenantByID(ctx context.Context, tenantID string) (RampTenant, error)
	// Idempotency lookup: return a prior transaction for the same tx_request_id.
	GetTransactionByRequestID(ctx context.Context, txRequestID string) (RampTransactionLog, error)
	InsertCatalogEntry(ctx context.Context, arg InsertCatalogEntryParams) (RampCatalog, error)
	InsertTenant(ctx context.Context, arg InsertTenantParams) (RampTenant, error)
	ListAllCatalog(ctx context.Context) ([]RampCatalog, error)
	ListCatalogByTenant(ctx context.Context, tenantID string) ([]RampCatalog, error)
	// Returns reporting obligations whose deadline has passed but which still
	// sit in PENDING for a specific (tenant_id, agent_id). Joins to
	// transaction_log because reporting_obligations does not carry tenant_id /
	// agent_id columns directly. The result drives the ExecuteTransaction
	// reporting-overdue refusal: a non-empty list refuses the agent's next
	// transaction with FailedPrecondition until it files the missing report.
	ListOutstandingObligations(ctx context.Context, arg ListOutstandingObligationsParams) ([]RampReportingObligation, error)
	// Records the rejection outcome without changing obligation state. The audit
	// row is written for every rejection so disputes have a trail, but the
	// obligation stays PENDING and the caller may retry with a corrected report
	// until the deadline expires.
	MarkValidationRejected(ctx context.Context, arg MarkValidationRejectedParams) (RampReportingObligation, error)
	// Sets validation_outcome=VALIDATED, transitions state PENDING→RECEIVED, and
	// writes the consumed quantity + idempotency anchors. The state predicate is
	// the duplicate-report guard: a second report against an obligation already
	// in RECEIVED matches zero rows and the caller surfaces FailedPrecondition.
	// The partial unique index on (transaction_id, source_report_id) prevents
	// two concurrent "same-id" writes from both succeeding.
	MarkValidationValidated(ctx context.Context, arg MarkValidationValidatedParams) (RampReportingObligation, error)
	// Flips the broker-relay opt-in for a tenant. Admin / fixture path; the
	// column defaults to FALSE on insert so this is only needed when a tenant
	// explicitly opts into broker-on-behalf reporting.
	SetTenantAllowBrokerRelay(ctx context.Context, arg SetTenantAllowBrokerRelayParams) error
	// Replaces the reporting_policy JSONB for a tenant. Admin / fixture path
	// for tests that need to seed required_fields, quantity_tolerance, or
	// window_seconds defaults without bypassing the repo layer (review
	// finding 7 — no raw pool.Exec in tests).
	SetTenantReportingPolicy(ctx context.Context, arg SetTenantReportingPolicyParams) error
	UpsertAgent(ctx context.Context, arg UpsertAgentParams) (RampAgent, error)
	UpsertCatalogEntry(ctx context.Context, arg UpsertCatalogEntryParams) (RampCatalog, error)
}

var _ Querier = (*Queries)(nil)
