// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reporting_obligations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createObligation = `-- name: CreateObligation :one
INSERT INTO ramp.reporting_obligations (
    obligation_id, transaction_id, state, window_seconds, deadline
) VALUES ($1, $2, $3, $4, $5)
RETURNING obligation_id, transaction_id, state, window_seconds, deadline, consumed_quantity, received_at, created_at
`

type CreateObligationParams struct {
	ObligationID  string              `json:"obligation_id"`
	TransactionID string              `json:"transaction_id"`
	State         RampObligationState `json:"state"`
	WindowSeconds pgtype.Int4         `json:"window_seconds"`
	Deadline      pgtype.Timestamptz  `json:"deadline"`
}

func (q *Queries) CreateObligation(ctx context.Context, arg CreateObligationParams) (RampReportingObligation, error) {
	row := q.db.QueryRow(ctx, createObligation,
		arg.ObligationID,
		arg.TransactionID,
		arg.State,
		arg.WindowSeconds,
		arg.Deadline,
	)
	var i RampReportingObligation
	err := row.Scan(
		&i.ObligationID,
		&i.TransactionID,
		&i.State,
		&i.WindowSeconds,
		&i.Deadline,
		&i.ConsumedQuantity,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getObligationByTransaction = `-- name: GetObligationByTransaction :one
SELECT obligation_id, transaction_id, state, window_seconds, deadline, consumed_quantity, received_at, created_at FROM ramp.reporting_obligations
 WHERE transaction_id = $1
 ORDER BY created_at DESC
 LIMIT 1
`

func (q *Queries) GetObligationByTransaction(ctx context.Context, transactionID string) (RampReportingObligation, error) {
	row := q.db.QueryRow(ctx, getObligationByTransaction, transactionID)
	var i RampReportingObligation
	err := row.Scan(
		&i.ObligationID,
		&i.TransactionID,
		&i.State,
		&i.WindowSeconds,
		&i.Deadline,
		&i.ConsumedQuantity,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markObligationReceived = `-- name: MarkObligationReceived :one
UPDATE ramp.reporting_obligations
   SET state = 'RECEIVED',
       consumed_quantity = $2,
       received_at = NOW()
 WHERE obligation_id = $1
RETURNING obligation_id, transaction_id, state, window_seconds, deadline, consumed_quantity, received_at, created_at
`

type MarkObligationReceivedParams struct {
	ObligationID     string         `json:"obligation_id"`
	ConsumedQuantity pgtype.Numeric `json:"consumed_quantity"`
}

func (q *Queries) MarkObligationReceived(ctx context.Context, arg MarkObligationReceivedParams) (RampReportingObligation, error) {
	row := q.db.QueryRow(ctx, markObligationReceived, arg.ObligationID, arg.ConsumedQuantity)
	var i RampReportingObligation
	err := row.Scan(
		&i.ObligationID,
		&i.TransactionID,
		&i.State,
		&i.WindowSeconds,
		&i.Deadline,
		&i.ConsumedQuantity,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}
