// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reporting_obligations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createObligation = `-- name: CreateObligation :one
INSERT INTO ramp.reporting_obligations (
    obligation_id, transaction_id, state, window_seconds, deadline,
    required_fields, estimated_quantity, quantity_tolerance
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING obligation_id, transaction_id, state, window_seconds, deadline, consumed_quantity, received_at, created_at, required_fields, estimated_quantity, quantity_tolerance, validation_outcome, validated_at, source_report_id, issued_report_id
`

type CreateObligationParams struct {
	ObligationID      string              `json:"obligation_id"`
	TransactionID     string              `json:"transaction_id"`
	State             RampObligationState `json:"state"`
	WindowSeconds     pgtype.Int4         `json:"window_seconds"`
	Deadline          pgtype.Timestamptz  `json:"deadline"`
	RequiredFields    []string            `json:"required_fields"`
	EstimatedQuantity int64               `json:"estimated_quantity"`
	QuantityTolerance pgtype.Numeric      `json:"quantity_tolerance"`
}

func (q *Queries) CreateObligation(ctx context.Context, arg CreateObligationParams) (RampReportingObligation, error) {
	row := q.db.QueryRow(ctx, createObligation,
		arg.ObligationID,
		arg.TransactionID,
		arg.State,
		arg.WindowSeconds,
		arg.Deadline,
		arg.RequiredFields,
		arg.EstimatedQuantity,
		arg.QuantityTolerance,
	)
	var i RampReportingObligation
	err := row.Scan(
		&i.ObligationID,
		&i.TransactionID,
		&i.State,
		&i.WindowSeconds,
		&i.Deadline,
		&i.ConsumedQuantity,
		&i.ReceivedAt,
		&i.CreatedAt,
		&i.RequiredFields,
		&i.EstimatedQuantity,
		&i.QuantityTolerance,
		&i.ValidationOutcome,
		&i.ValidatedAt,
		&i.SourceReportID,
		&i.IssuedReportID,
	)
	return i, err
}

const findObligationBySourceReportID = `-- name: FindObligationBySourceReportID :one
SELECT obligation_id, transaction_id, state, window_seconds, deadline, consumed_quantity, received_at, created_at, required_fields, estimated_quantity, quantity_tolerance, validation_outcome, validated_at, source_report_id, issued_report_id FROM ramp.reporting_obligations
 WHERE transaction_id = $1
   AND source_report_id = $2
 LIMIT 1
`

type FindObligationBySourceReportIDParams struct {
	TransactionID  string      `json:"transaction_id"`
	SourceReportID pgtype.Text `json:"source_report_id"`
}

// Idempotent-retry probe for ReportUsage: returns the obligation row whose
// (transaction_id, source_report_id) pair was already recorded. A non-empty
// hit means the caller is replaying a prior UsageReport and the service must
// return the original issued_report_id without re-running validation.
func (q *Queries) FindObligationBySourceReportID(ctx context.Context, arg FindObligationBySourceReportIDParams) (RampReportingObligation, error) {
	row := q.db.QueryRow(ctx, findObligationBySourceReportID, arg.TransactionID, arg.SourceReportID)
	var i RampReportingObligation
	err := row.Scan(
		&i.ObligationID,
		&i.TransactionID,
		&i.State,
		&i.WindowSeconds,
		&i.Deadline,
		&i.ConsumedQuantity,
		&i.ReceivedAt,
		&i.CreatedAt,
		&i.RequiredFields,
		&i.EstimatedQuantity,
		&i.QuantityTolerance,
		&i.ValidationOutcome,
		&i.ValidatedAt,
		&i.SourceReportID,
		&i.IssuedReportID,
	)
	return i, err
}

const getObligationByTransaction = `-- name: GetObligationByTransaction :one
SELECT obligation_id, transaction_id, state, window_seconds, deadline, consumed_quantity, received_at, created_at, required_fields, estimated_quantity, quantity_tolerance, validation_outcome, validated_at, source_report_id, issued_report_id FROM ramp.reporting_obligations
 WHERE transaction_id = $1
 ORDER BY created_at DESC
 LIMIT 1
`

func (q *Queries) GetObligationByTransaction(ctx context.Context, transactionID string) (RampReportingObligation, error) {
	row := q.db.QueryRow(ctx, getObligationByTransaction, transactionID)
	var i RampReportingObligation
	err := row.Scan(
		&i.ObligationID,
		&i.TransactionID,
		&i.State,
		&i.WindowSeconds,
		&i.Deadline,
		&i.ConsumedQuantity,
		&i.ReceivedAt,
		&i.CreatedAt,
		&i.RequiredFields,
		&i.EstimatedQuantity,
		&i.QuantityTolerance,
		&i.ValidationOutcome,
		&i.ValidatedAt,
		&i.SourceReportID,
		&i.IssuedReportID,
	)
	return i, err
}

const getObligationWithTransaction = `-- name: GetObligationWithTransaction :one
SELECT ro.obligation_id, ro.transaction_id, ro.state, ro.window_seconds, ro.deadline,
       ro.consumed_quantity, ro.received_at, ro.created_at, ro.required_fields,
       ro.estimated_quantity, ro.quantity_tolerance, ro.validation_outcome, ro.validated_at,
       ro.source_report_id, ro.issued_report_id,
       tl.created_at        AS tx_created_at,
       tl.billing_id        AS tx_billing_id,
       tl.tenant_id         AS tx_tenant_id,
       tl.agent_id          AS tx_agent_id,
       t.allow_broker_relay AS tenant_allow_broker_relay
  FROM ramp.reporting_obligations ro
  JOIN ramp.transaction_log tl ON tl.transaction_id = ro.transaction_id
  JOIN ramp.tenants          t ON t.tenant_id        = tl.tenant_id
 WHERE ro.transaction_id = $1
 ORDER BY ro.created_at DESC
 LIMIT 1
`

type GetObligationWithTransactionRow struct {
	ObligationID           string                    `json:"obligation_id"`
	TransactionID          string                    `json:"transaction_id"`
	State                  RampObligationState       `json:"state"`
	WindowSeconds          pgtype.Int4               `json:"window_seconds"`
	Deadline               pgtype.Timestamptz        `json:"deadline"`
	ConsumedQuantity       pgtype.Numeric            `json:"consumed_quantity"`
	ReceivedAt             pgtype.Timestamptz        `json:"received_at"`
	CreatedAt              pgtype.Timestamptz        `json:"created_at"`
	RequiredFields         []string                  `json:"required_fields"`
	EstimatedQuantity      int64                     `json:"estimated_quantity"`
	QuantityTolerance      pgtype.Numeric            `json:"quantity_tolerance"`
	ValidationOutcome      NullRampValidationOutcome `json:"validation_outcome"`
	ValidatedAt            pgtype.Timestamptz        `json:"validated_at"`
	SourceReportID         pgtype.Text               `json:"source_report_id"`
	IssuedReportID         pgtype.Text               `json:"issued_report_id"`
	TxCreatedAt            pgtype.Timestamptz        `json:"tx_created_at"`
	TxBillingID            pgtype.Text               `json:"tx_billing_id"`
	TxTenantID             string                    `json:"tx_tenant_id"`
	TxAgentID              string                    `json:"tx_agent_id"`
	TenantAllowBrokerRelay bool                      `json:"tenant_allow_broker_relay"`
}

// Loads the most-recent obligation for a transaction together with the
// transaction + tenant fields required for protocol validation AND for the
// caller-identity / broker-relay authorization checks. Single round-trip
// for ReportUsage's pre-persist validation; the *ForUpdate variant below
// locks the obligation row so concurrent reports cannot race the state
// transition.
func (q *Queries) GetObligationWithTransaction(ctx context.Context, transactionID string) (GetObligationWithTransactionRow, error) {
	row := q.db.QueryRow(ctx, getObligationWithTransaction, transactionID)
	var i GetObligationWithTransactionRow
	err := row.Scan(
		&i.ObligationID,
		&i.TransactionID,
		&i.State,
		&i.WindowSeconds,
		&i.Deadline,
		&i.ConsumedQuantity,
		&i.ReceivedAt,
		&i.CreatedAt,
		&i.RequiredFields,
		&i.EstimatedQuantity,
		&i.QuantityTolerance,
		&i.ValidationOutcome,
		&i.ValidatedAt,
		&i.SourceReportID,
		&i.IssuedReportID,
		&i.TxCreatedAt,
		&i.TxBillingID,
		&i.TxTenantID,
		&i.TxAgentID,
		&i.TenantAllowBrokerRelay,
	)
	return i, err
}

const getObligationWithTransactionForUpdate = `-- name: GetObligationWithTransactionForUpdate :one
SELECT ro.obligation_id, ro.transaction_id, ro.state, ro.window_seconds, ro.deadline,
       ro.consumed_quantity, ro.received_at, ro.created_at, ro.required_fields,
       ro.estimated_quantity, ro.quantity_tolerance, ro.validation_outcome, ro.validated_at,
       ro.source_report_id, ro.issued_report_id,
       tl.created_at        AS tx_created_at,
       tl.billing_id        AS tx_billing_id,
       tl.tenant_id         AS tx_tenant_id,
       tl.agent_id          AS tx_agent_id,
       t.allow_broker_relay AS tenant_allow_broker_relay
  FROM ramp.reporting_obligations ro
  JOIN ramp.transaction_log tl ON tl.transaction_id = ro.transaction_id
  JOIN ramp.tenants          t ON t.tenant_id        = tl.tenant_id
 WHERE ro.transaction_id = $1
 ORDER BY ro.created_at DESC
 LIMIT 1
 FOR UPDATE OF ro
`

type GetObligationWithTransactionForUpdateRow struct {
	ObligationID           string                    `json:"obligation_id"`
	TransactionID          string                    `json:"transaction_id"`
	State                  RampObligationState       `json:"state"`
	WindowSeconds          pgtype.Int4               `json:"window_seconds"`
	Deadline               pgtype.Timestamptz        `json:"deadline"`
	ConsumedQuantity       pgtype.Numeric            `json:"consumed_quantity"`
	ReceivedAt             pgtype.Timestamptz        `json:"received_at"`
	CreatedAt              pgtype.Timestamptz        `json:"created_at"`
	RequiredFields         []string                  `json:"required_fields"`
	EstimatedQuantity      int64                     `json:"estimated_quantity"`
	QuantityTolerance      pgtype.Numeric            `json:"quantity_tolerance"`
	ValidationOutcome      NullRampValidationOutcome `json:"validation_outcome"`
	ValidatedAt            pgtype.Timestamptz        `json:"validated_at"`
	SourceReportID         pgtype.Text               `json:"source_report_id"`
	IssuedReportID         pgtype.Text               `json:"issued_report_id"`
	TxCreatedAt            pgtype.Timestamptz        `json:"tx_created_at"`
	TxBillingID            pgtype.Text               `json:"tx_billing_id"`
	TxTenantID             string                    `json:"tx_tenant_id"`
	TxAgentID              string                    `json:"tx_agent_id"`
	TenantAllowBrokerRelay bool                      `json:"tenant_allow_broker_relay"`
}

// Same join as GetObligationWithTransaction but locks the obligation row for
// the duration of the surrounding transaction. ReportUsage uses this inside
// pgx.BeginFunc so the load/validate/write happens atomically against a held
// row. The transaction_log + tenants rows are read-only
// on this path and need no lock.
func (q *Queries) GetObligationWithTransactionForUpdate(ctx context.Context, transactionID string) (GetObligationWithTransactionForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getObligationWithTransactionForUpdate, transactionID)
	var i GetObligationWithTransactionForUpdateRow
	err := row.Scan(
		&i.ObligationID,
		&i.TransactionID,
		&i.State,
		&i.WindowSeconds,
		&i.Deadline,
		&i.ConsumedQuantity,
		&i.ReceivedAt,
		&i.CreatedAt,
		&i.RequiredFields,
		&i.EstimatedQuantity,
		&i.QuantityTolerance,
		&i.ValidationOutcome,
		&i.ValidatedAt,
		&i.SourceReportID,
		&i.IssuedReportID,
		&i.TxCreatedAt,
		&i.TxBillingID,
		&i.TxTenantID,
		&i.TxAgentID,
		&i.TenantAllowBrokerRelay,
	)
	return i, err
}

const listOutstandingObligations = `-- name: ListOutstandingObligations :many
SELECT ro.obligation_id, ro.transaction_id, ro.state, ro.window_seconds,
       ro.deadline, ro.consumed_quantity, ro.received_at, ro.created_at,
       ro.required_fields, ro.estimated_quantity, ro.quantity_tolerance,
       ro.validation_outcome, ro.validated_at,
       ro.source_report_id, ro.issued_report_id
  FROM ramp.reporting_obligations AS ro
  JOIN ramp.transaction_log AS tl ON tl.transaction_id = ro.transaction_id
 WHERE tl.tenant_id = $1
   AND tl.agent_id = $2
   AND ro.state = 'PENDING'
   AND ro.deadline < NOW()
 ORDER BY ro.deadline ASC
`

type ListOutstandingObligationsParams struct {
	TenantID string `json:"tenant_id"`
	AgentID  string `json:"agent_id"`
}

// Returns reporting obligations whose deadline has passed but which still
// sit in PENDING for a specific (tenant_id, agent_id). Joins to
// transaction_log because reporting_obligations does not carry tenant_id /
// agent_id columns directly. The result drives the AcceptOffer
// outstanding-obligations gate: a non-empty list refuses new accepts
// with a usage-family reason until the agent files the missing report.
func (q *Queries) ListOutstandingObligations(ctx context.Context, arg ListOutstandingObligationsParams) ([]RampReportingObligation, error) {
	rows, err := q.db.Query(ctx, listOutstandingObligations, arg.TenantID, arg.AgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RampReportingObligation{}
	for rows.Next() {
		var i RampReportingObligation
		if err := rows.Scan(
			&i.ObligationID,
			&i.TransactionID,
			&i.State,
			&i.WindowSeconds,
			&i.Deadline,
			&i.ConsumedQuantity,
			&i.ReceivedAt,
			&i.CreatedAt,
			&i.RequiredFields,
			&i.EstimatedQuantity,
			&i.QuantityTolerance,
			&i.ValidationOutcome,
			&i.ValidatedAt,
			&i.SourceReportID,
			&i.IssuedReportID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markValidationRejected = `-- name: MarkValidationRejected :one
UPDATE ramp.reporting_obligations
   SET validation_outcome = $2,
       validated_at       = NOW(),
       source_report_id   = COALESCE($3, source_report_id)
 WHERE obligation_id = $1
RETURNING obligation_id, transaction_id, state, window_seconds, deadline, consumed_quantity, received_at, created_at, required_fields, estimated_quantity, quantity_tolerance, validation_outcome, validated_at, source_report_id, issued_report_id
`

type MarkValidationRejectedParams struct {
	ObligationID      string                    `json:"obligation_id"`
	ValidationOutcome NullRampValidationOutcome `json:"validation_outcome"`
	SourceReportID    pgtype.Text               `json:"source_report_id"`
}

// Records the rejection outcome without changing obligation state. The audit
// row is written for every rejection so disputes have a trail, but the
// obligation stays PENDING and the caller may retry with a corrected report
// until the deadline expires.
func (q *Queries) MarkValidationRejected(ctx context.Context, arg MarkValidationRejectedParams) (RampReportingObligation, error) {
	row := q.db.QueryRow(ctx, markValidationRejected, arg.ObligationID, arg.ValidationOutcome, arg.SourceReportID)
	var i RampReportingObligation
	err := row.Scan(
		&i.ObligationID,
		&i.TransactionID,
		&i.State,
		&i.WindowSeconds,
		&i.Deadline,
		&i.ConsumedQuantity,
		&i.ReceivedAt,
		&i.CreatedAt,
		&i.RequiredFields,
		&i.EstimatedQuantity,
		&i.QuantityTolerance,
		&i.ValidationOutcome,
		&i.ValidatedAt,
		&i.SourceReportID,
		&i.IssuedReportID,
	)
	return i, err
}

const markValidationValidated = `-- name: MarkValidationValidated :one
UPDATE ramp.reporting_obligations
   SET state              = 'RECEIVED',
       consumed_quantity  = $2,
       received_at        = NOW(),
       validation_outcome = 'VALIDATED',
       validated_at       = NOW(),
       source_report_id   = $3,
       issued_report_id   = $4
 WHERE obligation_id = $1
   AND state         = 'PENDING'
RETURNING obligation_id, transaction_id, state, window_seconds, deadline, consumed_quantity, received_at, created_at, required_fields, estimated_quantity, quantity_tolerance, validation_outcome, validated_at, source_report_id, issued_report_id
`

type MarkValidationValidatedParams struct {
	ObligationID     string         `json:"obligation_id"`
	ConsumedQuantity pgtype.Numeric `json:"consumed_quantity"`
	SourceReportID   pgtype.Text    `json:"source_report_id"`
	IssuedReportID   pgtype.Text    `json:"issued_report_id"`
}

// Sets validation_outcome=VALIDATED, transitions state PENDING→RECEIVED, and
// writes the consumed quantity + idempotency anchors. The state predicate is
// the duplicate-report guard: a second report against an obligation already
// in RECEIVED matches zero rows and the caller surfaces FailedPrecondition.
// The partial unique index on (transaction_id, source_report_id) prevents
// two concurrent "same-id" writes from both succeeding.
func (q *Queries) MarkValidationValidated(ctx context.Context, arg MarkValidationValidatedParams) (RampReportingObligation, error) {
	row := q.db.QueryRow(ctx, markValidationValidated,
		arg.ObligationID,
		arg.ConsumedQuantity,
		arg.SourceReportID,
		arg.IssuedReportID,
	)
	var i RampReportingObligation
	err := row.Scan(
		&i.ObligationID,
		&i.TransactionID,
		&i.State,
		&i.WindowSeconds,
		&i.Deadline,
		&i.ConsumedQuantity,
		&i.ReceivedAt,
		&i.CreatedAt,
		&i.RequiredFields,
		&i.EstimatedQuantity,
		&i.QuantityTolerance,
		&i.ValidationOutcome,
		&i.ValidatedAt,
		&i.SourceReportID,
		&i.IssuedReportID,
	)
	return i, err
}
