// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTenantByDomain = `-- name: GetTenantByDomain :one
SELECT tenant_id, domain, hmac_secret_ref, ed25519_key_ref, reporting_policy, created_at, signing_scheme, rsa_key_ref, cloudfront_key_pair_id, allow_broker_relay FROM ramp.tenants WHERE domain = $1
`

func (q *Queries) GetTenantByDomain(ctx context.Context, domain string) (RampTenant, error) {
	row := q.db.QueryRow(ctx, getTenantByDomain, domain)
	var i RampTenant
	err := row.Scan(
		&i.TenantID,
		&i.Domain,
		&i.HmacSecretRef,
		&i.Ed25519KeyRef,
		&i.ReportingPolicy,
		&i.CreatedAt,
		&i.SigningScheme,
		&i.RsaKeyRef,
		&i.CloudfrontKeyPairID,
		&i.AllowBrokerRelay,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT tenant_id, domain, hmac_secret_ref, ed25519_key_ref, reporting_policy, created_at, signing_scheme, rsa_key_ref, cloudfront_key_pair_id, allow_broker_relay FROM ramp.tenants WHERE tenant_id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, tenantID string) (RampTenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, tenantID)
	var i RampTenant
	err := row.Scan(
		&i.TenantID,
		&i.Domain,
		&i.HmacSecretRef,
		&i.Ed25519KeyRef,
		&i.ReportingPolicy,
		&i.CreatedAt,
		&i.SigningScheme,
		&i.RsaKeyRef,
		&i.CloudfrontKeyPairID,
		&i.AllowBrokerRelay,
	)
	return i, err
}

const insertTenant = `-- name: InsertTenant :one
INSERT INTO ramp.tenants (
    tenant_id, domain, hmac_secret_ref, ed25519_key_ref, reporting_policy,
    signing_scheme, rsa_key_ref, cloudfront_key_pair_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING tenant_id, domain, hmac_secret_ref, ed25519_key_ref, reporting_policy, created_at, signing_scheme, rsa_key_ref, cloudfront_key_pair_id, allow_broker_relay
`

type InsertTenantParams struct {
	TenantID            string            `json:"tenant_id"`
	Domain              string            `json:"domain"`
	HmacSecretRef       string            `json:"hmac_secret_ref"`
	Ed25519KeyRef       string            `json:"ed25519_key_ref"`
	ReportingPolicy     []byte            `json:"reporting_policy"`
	SigningScheme       RampSigningScheme `json:"signing_scheme"`
	RsaKeyRef           pgtype.Text       `json:"rsa_key_ref"`
	CloudfrontKeyPairID pgtype.Text       `json:"cloudfront_key_pair_id"`
}

func (q *Queries) InsertTenant(ctx context.Context, arg InsertTenantParams) (RampTenant, error) {
	row := q.db.QueryRow(ctx, insertTenant,
		arg.TenantID,
		arg.Domain,
		arg.HmacSecretRef,
		arg.Ed25519KeyRef,
		arg.ReportingPolicy,
		arg.SigningScheme,
		arg.RsaKeyRef,
		arg.CloudfrontKeyPairID,
	)
	var i RampTenant
	err := row.Scan(
		&i.TenantID,
		&i.Domain,
		&i.HmacSecretRef,
		&i.Ed25519KeyRef,
		&i.ReportingPolicy,
		&i.CreatedAt,
		&i.SigningScheme,
		&i.RsaKeyRef,
		&i.CloudfrontKeyPairID,
		&i.AllowBrokerRelay,
	)
	return i, err
}

const setTenantAllowBrokerRelay = `-- name: SetTenantAllowBrokerRelay :exec
UPDATE ramp.tenants
   SET allow_broker_relay = $2
 WHERE tenant_id = $1
`

type SetTenantAllowBrokerRelayParams struct {
	TenantID         string `json:"tenant_id"`
	AllowBrokerRelay bool   `json:"allow_broker_relay"`
}

// Flips the broker-relay opt-in for a tenant. Admin / fixture path; the
// column defaults to FALSE on insert so this is only needed when a tenant
// explicitly opts into broker-on-behalf reporting.
func (q *Queries) SetTenantAllowBrokerRelay(ctx context.Context, arg SetTenantAllowBrokerRelayParams) error {
	_, err := q.db.Exec(ctx, setTenantAllowBrokerRelay, arg.TenantID, arg.AllowBrokerRelay)
	return err
}

const setTenantReportingPolicy = `-- name: SetTenantReportingPolicy :exec
UPDATE ramp.tenants
   SET reporting_policy = $2
 WHERE tenant_id = $1
`

type SetTenantReportingPolicyParams struct {
	TenantID        string `json:"tenant_id"`
	ReportingPolicy []byte `json:"reporting_policy"`
}

// Replaces the reporting_policy JSONB for a tenant. Admin / fixture path
// for tests that need to seed required_fields, quantity_tolerance, or
// window_seconds defaults without bypassing the repo layer (review
// finding 7 — no raw pool.Exec in tests).
func (q *Queries) SetTenantReportingPolicy(ctx context.Context, arg SetTenantReportingPolicyParams) error {
	_, err := q.db.Exec(ctx, setTenantReportingPolicy, arg.TenantID, arg.ReportingPolicy)
	return err
}
