// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTenantByDomain = `-- name: GetTenantByDomain :one
SELECT tenant_id, domain, hmac_secret_ref, ed25519_key_ref, reporting_policy, created_at, signing_scheme, rsa_key_ref, cloudfront_key_pair_id FROM ramp.tenants WHERE domain = $1
`

func (q *Queries) GetTenantByDomain(ctx context.Context, domain string) (RampTenant, error) {
	row := q.db.QueryRow(ctx, getTenantByDomain, domain)
	var i RampTenant
	err := row.Scan(
		&i.TenantID,
		&i.Domain,
		&i.HmacSecretRef,
		&i.Ed25519KeyRef,
		&i.ReportingPolicy,
		&i.CreatedAt,
		&i.SigningScheme,
		&i.RsaKeyRef,
		&i.CloudfrontKeyPairID,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT tenant_id, domain, hmac_secret_ref, ed25519_key_ref, reporting_policy, created_at, signing_scheme, rsa_key_ref, cloudfront_key_pair_id FROM ramp.tenants WHERE tenant_id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, tenantID string) (RampTenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, tenantID)
	var i RampTenant
	err := row.Scan(
		&i.TenantID,
		&i.Domain,
		&i.HmacSecretRef,
		&i.Ed25519KeyRef,
		&i.ReportingPolicy,
		&i.CreatedAt,
		&i.SigningScheme,
		&i.RsaKeyRef,
		&i.CloudfrontKeyPairID,
	)
	return i, err
}

const insertTenant = `-- name: InsertTenant :one
INSERT INTO ramp.tenants (
    tenant_id, domain, hmac_secret_ref, ed25519_key_ref, reporting_policy,
    signing_scheme, rsa_key_ref, cloudfront_key_pair_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING tenant_id, domain, hmac_secret_ref, ed25519_key_ref, reporting_policy, created_at, signing_scheme, rsa_key_ref, cloudfront_key_pair_id
`

type InsertTenantParams struct {
	TenantID            string            `json:"tenant_id"`
	Domain              string            `json:"domain"`
	HmacSecretRef       string            `json:"hmac_secret_ref"`
	Ed25519KeyRef       string            `json:"ed25519_key_ref"`
	ReportingPolicy     []byte            `json:"reporting_policy"`
	SigningScheme       RampSigningScheme `json:"signing_scheme"`
	RsaKeyRef           pgtype.Text       `json:"rsa_key_ref"`
	CloudfrontKeyPairID pgtype.Text       `json:"cloudfront_key_pair_id"`
}

func (q *Queries) InsertTenant(ctx context.Context, arg InsertTenantParams) (RampTenant, error) {
	row := q.db.QueryRow(ctx, insertTenant,
		arg.TenantID,
		arg.Domain,
		arg.HmacSecretRef,
		arg.Ed25519KeyRef,
		arg.ReportingPolicy,
		arg.SigningScheme,
		arg.RsaKeyRef,
		arg.CloudfrontKeyPairID,
	)
	var i RampTenant
	err := row.Scan(
		&i.TenantID,
		&i.Domain,
		&i.HmacSecretRef,
		&i.Ed25519KeyRef,
		&i.ReportingPolicy,
		&i.CreatedAt,
		&i.SigningScheme,
		&i.RsaKeyRef,
		&i.CloudfrontKeyPairID,
	)
	return i, err
}
