// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_fee_overrides.sql

package sqlc

import (
	"context"
)

const getResourceOwnerFeeOverride = `-- name: GetResourceOwnerFeeOverride :one
SELECT fee_rate_bps FROM ramp.tenant_resource_owner_fee
 WHERE tenant_id = $1 AND resource_owner_id = $2
`

type GetResourceOwnerFeeOverrideParams struct {
	TenantID        string `json:"tenant_id"`
	ResourceOwnerID string `json:"resource_owner_id"`
}

// Returns the per-(tenant, resource_owner) commission override in basis points,
// or no row when none is configured (the caller falls back to the tenant default).
func (q *Queries) GetResourceOwnerFeeOverride(ctx context.Context, arg GetResourceOwnerFeeOverrideParams) (int32, error) {
	row := q.db.QueryRow(ctx, getResourceOwnerFeeOverride, arg.TenantID, arg.ResourceOwnerID)
	var fee_rate_bps int32
	err := row.Scan(&fee_rate_bps)
	return fee_rate_bps, err
}

const upsertResourceOwnerFeeOverride = `-- name: UpsertResourceOwnerFeeOverride :exec
INSERT INTO ramp.tenant_resource_owner_fee (tenant_id, resource_owner_id, fee_rate_bps)
VALUES ($1, $2, $3)
ON CONFLICT (tenant_id, resource_owner_id) DO UPDATE
    SET fee_rate_bps = EXCLUDED.fee_rate_bps,
        updated_at   = NOW()
`

type UpsertResourceOwnerFeeOverrideParams struct {
	TenantID        string `json:"tenant_id"`
	ResourceOwnerID string `json:"resource_owner_id"`
	FeeRateBps      int32  `json:"fee_rate_bps"`
}

// Sets the override commission for one resource owner under one tenant. Admin /
// fixture path; the CHECK (0 <= fee_rate_bps < 10000) rejects an out-of-range rate.
func (q *Queries) UpsertResourceOwnerFeeOverride(ctx context.Context, arg UpsertResourceOwnerFeeOverrideParams) error {
	_, err := q.db.Exec(ctx, upsertResourceOwnerFeeOverride, arg.TenantID, arg.ResourceOwnerID, arg.FeeRateBps)
	return err
}
