// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction_request_claims.sql

package sqlc

import (
	"context"
)

const finalizeTransactionRequestClaim = `-- name: FinalizeTransactionRequestClaim :execrows
UPDATE ramp.transaction_request_claims
   SET response_payload = $3
 WHERE agent_id = $1 AND idempotency_key = $2 AND response_payload IS NULL
`

type FinalizeTransactionRequestClaimParams struct {
	AgentID         string `json:"agent_id"`
	IdempotencyKey  string `json:"idempotency_key"`
	ResponsePayload []byte `json:"response_payload"`
}

func (q *Queries) FinalizeTransactionRequestClaim(ctx context.Context, arg FinalizeTransactionRequestClaimParams) (int64, error) {
	result, err := q.db.Exec(ctx, finalizeTransactionRequestClaim, arg.AgentID, arg.IdempotencyKey, arg.ResponsePayload)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTransactionRequestClaim = `-- name: GetTransactionRequestClaim :one
SELECT agent_id, idempotency_key, items_digest, created_at, response_payload FROM ramp.transaction_request_claims
 WHERE agent_id = $1 AND idempotency_key = $2
`

type GetTransactionRequestClaimParams struct {
	AgentID        string `json:"agent_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) GetTransactionRequestClaim(ctx context.Context, arg GetTransactionRequestClaimParams) (RampTransactionRequestClaim, error) {
	row := q.db.QueryRow(ctx, getTransactionRequestClaim, arg.AgentID, arg.IdempotencyKey)
	var i RampTransactionRequestClaim
	err := row.Scan(
		&i.AgentID,
		&i.IdempotencyKey,
		&i.ItemsDigest,
		&i.CreatedAt,
		&i.ResponsePayload,
	)
	return i, err
}

const insertTransactionRequestClaim = `-- name: InsertTransactionRequestClaim :execrows
INSERT INTO ramp.transaction_request_claims (agent_id, idempotency_key, items_digest)
VALUES ($1, $2, $3)
ON CONFLICT (agent_id, idempotency_key) DO NOTHING
`

type InsertTransactionRequestClaimParams struct {
	AgentID        string `json:"agent_id"`
	IdempotencyKey string `json:"idempotency_key"`
	ItemsDigest    []byte `json:"items_digest"`
}

func (q *Queries) InsertTransactionRequestClaim(ctx context.Context, arg InsertTransactionRequestClaimParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertTransactionRequestClaim, arg.AgentID, arg.IdempotencyKey, arg.ItemsDigest)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
