// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction_evidence.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvidence = `-- name: CreateEvidence :exec
INSERT INTO ramp.transaction_evidence (
    transaction_id, tenant_id,
    offer_id, offer_json, offer_canonical_bytes,
    offer_signature, offer_signature_algorithm, exchange_signing_public_key,
    agent_acceptance_signature, agent_acceptance_canonical_bytes,
    agent_acceptance_signature_algorithm,
    requester_id, requester_domain, request_idempotency_key,
    agent_public_key, agent_discovery_url,
    signed_url_full, request_id, request_id_minted
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19
)
`

type CreateEvidenceParams struct {
	TransactionID                     string      `json:"transaction_id"`
	TenantID                          string      `json:"tenant_id"`
	OfferID                           string      `json:"offer_id"`
	OfferJson                         []byte      `json:"offer_json"`
	OfferCanonicalBytes               []byte      `json:"offer_canonical_bytes"`
	OfferSignature                    string      `json:"offer_signature"`
	OfferSignatureAlgorithm           string      `json:"offer_signature_algorithm"`
	ExchangeSigningPublicKey          []byte      `json:"exchange_signing_public_key"`
	AgentAcceptanceSignature          string      `json:"agent_acceptance_signature"`
	AgentAcceptanceCanonicalBytes     []byte      `json:"agent_acceptance_canonical_bytes"`
	AgentAcceptanceSignatureAlgorithm string      `json:"agent_acceptance_signature_algorithm"`
	RequesterID                       string      `json:"requester_id"`
	RequesterDomain                   string      `json:"requester_domain"`
	RequestIdempotencyKey             string      `json:"request_idempotency_key"`
	AgentPublicKey                    []byte      `json:"agent_public_key"`
	AgentDiscoveryUrl                 string      `json:"agent_discovery_url"`
	SignedUrlFull                     string      `json:"signed_url_full"`
	RequestID                         pgtype.Text `json:"request_id"`
	RequestIDMinted                   pgtype.Bool `json:"request_id_minted"`
}

// Writes the append-once evidence row for a successfully executed transaction
// item: the full signed offer + both-party signatures + both verifying public
// keys + the delivered URL. Written inside the same transaction as the
// transaction_log + obligation rows, after the transaction_log row exists (the
// transaction_id FK). The row is never updated or deleted (append-once triggers).
func (q *Queries) CreateEvidence(ctx context.Context, arg CreateEvidenceParams) error {
	_, err := q.db.Exec(ctx, createEvidence,
		arg.TransactionID,
		arg.TenantID,
		arg.OfferID,
		arg.OfferJson,
		arg.OfferCanonicalBytes,
		arg.OfferSignature,
		arg.OfferSignatureAlgorithm,
		arg.ExchangeSigningPublicKey,
		arg.AgentAcceptanceSignature,
		arg.AgentAcceptanceCanonicalBytes,
		arg.AgentAcceptanceSignatureAlgorithm,
		arg.RequesterID,
		arg.RequesterDomain,
		arg.RequestIdempotencyKey,
		arg.AgentPublicKey,
		arg.AgentDiscoveryUrl,
		arg.SignedUrlFull,
		arg.RequestID,
		arg.RequestIDMinted,
	)
	return err
}

const getEvidenceByTenantAndTransactionID = `-- name: GetEvidenceByTenantAndTransactionID :one
SELECT transaction_id, tenant_id, offer_id, offer_json, offer_canonical_bytes, offer_signature, offer_signature_algorithm, exchange_signing_public_key, agent_acceptance_signature, agent_acceptance_canonical_bytes, agent_acceptance_signature_algorithm, requester_id, requester_domain, request_idempotency_key, agent_public_key, agent_discovery_url, signed_url_full, request_id, request_id_minted, created_at FROM ramp.transaction_evidence
WHERE tenant_id = $1 AND transaction_id = $2
`

type GetEvidenceByTenantAndTransactionIDParams struct {
	TenantID      string `json:"tenant_id"`
	TransactionID string `json:"transaction_id"`
}

// Reads one tenant's evidence row. This is the DEFAULT read: transaction_id is
// globally unique, but the tenant predicate keeps Architecture Rule 4 structural
// rather than a checked-by-convention property of every future call site. The
// payload here — the full offer, both signatures, both keys and a delivered
// signed URL — is materially more sensitive than transaction_log's.
func (q *Queries) GetEvidenceByTenantAndTransactionID(ctx context.Context, arg GetEvidenceByTenantAndTransactionIDParams) (RampTransactionEvidence, error) {
	row := q.db.QueryRow(ctx, getEvidenceByTenantAndTransactionID, arg.TenantID, arg.TransactionID)
	var i RampTransactionEvidence
	err := row.Scan(
		&i.TransactionID,
		&i.TenantID,
		&i.OfferID,
		&i.OfferJson,
		&i.OfferCanonicalBytes,
		&i.OfferSignature,
		&i.OfferSignatureAlgorithm,
		&i.ExchangeSigningPublicKey,
		&i.AgentAcceptanceSignature,
		&i.AgentAcceptanceCanonicalBytes,
		&i.AgentAcceptanceSignatureAlgorithm,
		&i.RequesterID,
		&i.RequesterDomain,
		&i.RequestIdempotencyKey,
		&i.AgentPublicKey,
		&i.AgentDiscoveryUrl,
		&i.SignedUrlFull,
		&i.RequestID,
		&i.RequestIDMinted,
		&i.CreatedAt,
	)
	return i, err
}

const getEvidenceByTransactionIDCrossTenant = `-- name: GetEvidenceByTransactionIDCrossTenant :one
SELECT transaction_id, tenant_id, offer_id, offer_json, offer_canonical_bytes, offer_signature, offer_signature_algorithm, exchange_signing_public_key, agent_acceptance_signature, agent_acceptance_canonical_bytes, agent_acceptance_signature_algorithm, requester_id, requester_domain, request_idempotency_key, agent_public_key, agent_discovery_url, signed_url_full, request_id, request_id_minted, created_at FROM ramp.transaction_evidence WHERE transaction_id = $1
`

// admin:cross_tenant — DELIBERATELY not tenant-filtered, for the operator-facing
// admin plane (which has no per-tenant scope, ADR-022) and the cross-tenant
// reconciliation sweep (ADR-011 D2, whose eligibility scan carries the same
// marker). Every call site must carry the marker too. Tenant-scoped callers use
// GetEvidenceByTenantAndTransactionID; the returned row carries tenant_id so a
// caller here can still assert the binding.
func (q *Queries) GetEvidenceByTransactionIDCrossTenant(ctx context.Context, transactionID string) (RampTransactionEvidence, error) {
	row := q.db.QueryRow(ctx, getEvidenceByTransactionIDCrossTenant, transactionID)
	var i RampTransactionEvidence
	err := row.Scan(
		&i.TransactionID,
		&i.TenantID,
		&i.OfferID,
		&i.OfferJson,
		&i.OfferCanonicalBytes,
		&i.OfferSignature,
		&i.OfferSignatureAlgorithm,
		&i.ExchangeSigningPublicKey,
		&i.AgentAcceptanceSignature,
		&i.AgentAcceptanceCanonicalBytes,
		&i.AgentAcceptanceSignatureAlgorithm,
		&i.RequesterID,
		&i.RequesterDomain,
		&i.RequestIdempotencyKey,
		&i.AgentPublicKey,
		&i.AgentDiscoveryUrl,
		&i.SignedUrlFull,
		&i.RequestID,
		&i.RequestIDMinted,
		&i.CreatedAt,
	)
	return i, err
}
