// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exchanges.sql

package sqlc

import (
	"context"
)

const listActiveExchanges = `-- name: ListActiveExchanges :many
SELECT exchange_id, domain, endpoint, trust_level, healthy, supported_profiles, priority, last_health_check, created_at, updated_at FROM broker.exchanges
 WHERE healthy = TRUE AND trust_level != 'BLOCKED'
 ORDER BY priority DESC, trust_level
`

func (q *Queries) ListActiveExchanges(ctx context.Context) ([]BrokerExchange, error) {
	rows, err := q.db.Query(ctx, listActiveExchanges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BrokerExchange{}
	for rows.Next() {
		var i BrokerExchange
		if err := rows.Scan(
			&i.ExchangeID,
			&i.Domain,
			&i.Endpoint,
			&i.TrustLevel,
			&i.Healthy,
			&i.SupportedProfiles,
			&i.Priority,
			&i.LastHealthCheck,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExchange = `-- name: UpsertExchange :one
INSERT INTO broker.exchanges (
    exchange_id, domain, endpoint, trust_level, supported_profiles, priority
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (exchange_id) DO UPDATE
    SET domain = EXCLUDED.domain,
        endpoint = EXCLUDED.endpoint,
        trust_level = EXCLUDED.trust_level,
        supported_profiles = EXCLUDED.supported_profiles,
        priority = EXCLUDED.priority,
        updated_at = NOW()
RETURNING exchange_id, domain, endpoint, trust_level, healthy, supported_profiles, priority, last_health_check, created_at, updated_at
`

type UpsertExchangeParams struct {
	ExchangeID        string           `json:"exchange_id"`
	Domain            string           `json:"domain"`
	Endpoint          string           `json:"endpoint"`
	TrustLevel        BrokerTrustLevel `json:"trust_level"`
	SupportedProfiles []byte           `json:"supported_profiles"`
	Priority          int32            `json:"priority"`
}

func (q *Queries) UpsertExchange(ctx context.Context, arg UpsertExchangeParams) (BrokerExchange, error) {
	row := q.db.QueryRow(ctx, upsertExchange,
		arg.ExchangeID,
		arg.Domain,
		arg.Endpoint,
		arg.TrustLevel,
		arg.SupportedProfiles,
		arg.Priority,
	)
	var i BrokerExchange
	err := row.Scan(
		&i.ExchangeID,
		&i.Domain,
		&i.Endpoint,
		&i.TrustLevel,
		&i.Healthy,
		&i.SupportedProfiles,
		&i.Priority,
		&i.LastHealthCheck,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
