// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: marketplaces.sql

package sqlc

import (
	"context"
)

const listActiveMarketplaces = `-- name: ListActiveMarketplaces :many
SELECT marketplace_id, domain, endpoint, trust_level, healthy, supported_profiles, priority, last_health_check, created_at, updated_at FROM broker.marketplaces
 WHERE healthy = TRUE AND trust_level != 'BLOCKED'
 ORDER BY priority DESC, trust_level
`

func (q *Queries) ListActiveMarketplaces(ctx context.Context) ([]BrokerMarketplace, error) {
	rows, err := q.db.Query(ctx, listActiveMarketplaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BrokerMarketplace{}
	for rows.Next() {
		var i BrokerMarketplace
		if err := rows.Scan(
			&i.MarketplaceID,
			&i.Domain,
			&i.Endpoint,
			&i.TrustLevel,
			&i.Healthy,
			&i.SupportedProfiles,
			&i.Priority,
			&i.LastHealthCheck,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMarketplace = `-- name: UpsertMarketplace :one
INSERT INTO broker.marketplaces (
    marketplace_id, domain, endpoint, trust_level, supported_profiles, priority
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (marketplace_id) DO UPDATE
    SET domain = EXCLUDED.domain,
        endpoint = EXCLUDED.endpoint,
        trust_level = EXCLUDED.trust_level,
        supported_profiles = EXCLUDED.supported_profiles,
        priority = EXCLUDED.priority,
        updated_at = NOW()
RETURNING marketplace_id, domain, endpoint, trust_level, healthy, supported_profiles, priority, last_health_check, created_at, updated_at
`

type UpsertMarketplaceParams struct {
	MarketplaceID     string           `json:"marketplace_id"`
	Domain            string           `json:"domain"`
	Endpoint          string           `json:"endpoint"`
	TrustLevel        BrokerTrustLevel `json:"trust_level"`
	SupportedProfiles []byte           `json:"supported_profiles"`
	Priority          int32            `json:"priority"`
}

func (q *Queries) UpsertMarketplace(ctx context.Context, arg UpsertMarketplaceParams) (BrokerMarketplace, error) {
	row := q.db.QueryRow(ctx, upsertMarketplace,
		arg.MarketplaceID,
		arg.Domain,
		arg.Endpoint,
		arg.TrustLevel,
		arg.SupportedProfiles,
		arg.Priority,
	)
	var i BrokerMarketplace
	err := row.Scan(
		&i.MarketplaceID,
		&i.Domain,
		&i.Endpoint,
		&i.TrustLevel,
		&i.Healthy,
		&i.SupportedProfiles,
		&i.Priority,
		&i.LastHealthCheck,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
