// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type BrokerTrustLevel string

const (
	BrokerTrustLevelDISCOVERED BrokerTrustLevel = "DISCOVERED"
	BrokerTrustLevelVERIFIED   BrokerTrustLevel = "VERIFIED"
	BrokerTrustLevelPREFERRED  BrokerTrustLevel = "PREFERRED"
	BrokerTrustLevelBLOCKED    BrokerTrustLevel = "BLOCKED"
)

func (e *BrokerTrustLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BrokerTrustLevel(s)
	case string:
		*e = BrokerTrustLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for BrokerTrustLevel: %T", src)
	}
	return nil
}

type NullBrokerTrustLevel struct {
	BrokerTrustLevel BrokerTrustLevel `json:"broker_trust_level"`
	Valid            bool             `json:"valid"` // Valid is true if BrokerTrustLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBrokerTrustLevel) Scan(value interface{}) error {
	if value == nil {
		ns.BrokerTrustLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BrokerTrustLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBrokerTrustLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BrokerTrustLevel), nil
}

func (e BrokerTrustLevel) Valid() bool {
	switch e {
	case BrokerTrustLevelDISCOVERED,
		BrokerTrustLevelVERIFIED,
		BrokerTrustLevelPREFERRED,
		BrokerTrustLevelBLOCKED:
		return true
	}
	return false
}

type BrokerExchange struct {
	ExchangeID        string             `json:"exchange_id"`
	Domain            string             `json:"domain"`
	Endpoint          string             `json:"endpoint"`
	TrustLevel        BrokerTrustLevel   `json:"trust_level"`
	Healthy           bool               `json:"healthy"`
	SupportedProfiles []byte             `json:"supported_profiles"`
	Priority          int32              `json:"priority"`
	LastHealthCheck   pgtype.Timestamptz `json:"last_health_check"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type BrokerSelectionLog struct {
	LogID           string             `json:"log_id"`
	RequestID       string             `json:"request_id"`
	AgentID         string             `json:"agent_id"`
	Query           string             `json:"query"`
	CandidateOffers []byte             `json:"candidate_offers"`
	Rationale       []byte             `json:"rationale"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}
