// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	ListActiveMarketplaces(ctx context.Context) ([]BrokerMarketplace, error)
	RecordSelection(ctx context.Context, arg RecordSelectionParams) (BrokerSelectionLog, error)
	UpsertMarketplace(ctx context.Context, arg UpsertMarketplaceParams) (BrokerMarketplace, error)
}

var _ Querier = (*Queries)(nil)
