// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	ListActiveExchanges(ctx context.Context) ([]BrokerExchange, error)
	RecordSelection(ctx context.Context, arg RecordSelectionParams) (BrokerSelectionLog, error)
	SelectionsByRequestID(ctx context.Context, requestID string) ([]BrokerSelectionLog, error)
	UpsertExchange(ctx context.Context, arg UpsertExchangeParams) (BrokerExchange, error)
}

var _ Querier = (*Queries)(nil)
