// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: selection_log.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const recordSelection = `-- name: RecordSelection :one
INSERT INTO broker.selection_log (
    log_id, request_id, agent_id, query, candidate_offers,
    winner_offer_id, winner_exchange, rationale
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING log_id, request_id, agent_id, query, candidate_offers, winner_offer_id, winner_exchange, rationale, created_at
`

type RecordSelectionParams struct {
	LogID           string      `json:"log_id"`
	RequestID       string      `json:"request_id"`
	AgentID         string      `json:"agent_id"`
	Query           string      `json:"query"`
	CandidateOffers []byte      `json:"candidate_offers"`
	WinnerOfferID   pgtype.Text `json:"winner_offer_id"`
	WinnerExchange  pgtype.Text `json:"winner_exchange"`
	Rationale       []byte      `json:"rationale"`
}

func (q *Queries) RecordSelection(ctx context.Context, arg RecordSelectionParams) (BrokerSelectionLog, error) {
	row := q.db.QueryRow(ctx, recordSelection,
		arg.LogID,
		arg.RequestID,
		arg.AgentID,
		arg.Query,
		arg.CandidateOffers,
		arg.WinnerOfferID,
		arg.WinnerExchange,
		arg.Rationale,
	)
	var i BrokerSelectionLog
	err := row.Scan(
		&i.LogID,
		&i.RequestID,
		&i.AgentID,
		&i.Query,
		&i.CandidateOffers,
		&i.WinnerOfferID,
		&i.WinnerExchange,
		&i.Rationale,
		&i.CreatedAt,
	)
	return i, err
}
