// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: selection_log.sql

package sqlc

import (
	"context"
)

const recordSelection = `-- name: RecordSelection :one
INSERT INTO broker.selection_log (
    log_id, request_id, agent_id, query, candidate_offers, rationale
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING log_id, request_id, agent_id, query, candidate_offers, rationale, created_at
`

type RecordSelectionParams struct {
	LogID           string `json:"log_id"`
	RequestID       string `json:"request_id"`
	AgentID         string `json:"agent_id"`
	Query           string `json:"query"`
	CandidateOffers []byte `json:"candidate_offers"`
	Rationale       []byte `json:"rationale"`
}

func (q *Queries) RecordSelection(ctx context.Context, arg RecordSelectionParams) (BrokerSelectionLog, error) {
	row := q.db.QueryRow(ctx, recordSelection,
		arg.LogID,
		arg.RequestID,
		arg.AgentID,
		arg.Query,
		arg.CandidateOffers,
		arg.Rationale,
	)
	var i BrokerSelectionLog
	err := row.Scan(
		&i.LogID,
		&i.RequestID,
		&i.AgentID,
		&i.Query,
		&i.CandidateOffers,
		&i.Rationale,
		&i.CreatedAt,
	)
	return i, err
}

const selectionsByRequestID = `-- name: SelectionsByRequestID :many
SELECT log_id, request_id, agent_id, query, candidate_offers, rationale, created_at FROM broker.selection_log
WHERE request_id = $1
ORDER BY created_at DESC
`

func (q *Queries) SelectionsByRequestID(ctx context.Context, requestID string) ([]BrokerSelectionLog, error) {
	rows, err := q.db.Query(ctx, selectionsByRequestID, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BrokerSelectionLog{}
	for rows.Next() {
		var i BrokerSelectionLog
		if err := rows.Scan(
			&i.LogID,
			&i.RequestID,
			&i.AgentID,
			&i.Query,
			&i.CandidateOffers,
			&i.Rationale,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
