// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_accounts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAgentAccountActive = `-- name: GetAgentAccountActive :one
SELECT active FROM sor.agent_accounts WHERE billing_ref = $1
`

func (q *Queries) GetAgentAccountActive(ctx context.Context, billingRef string) (bool, error) {
	row := q.db.QueryRow(ctx, getAgentAccountActive, billingRef)
	var active bool
	err := row.Scan(&active)
	return active, err
}

const getAgentAccountBySubdomain = `-- name: GetAgentAccountBySubdomain :one
SELECT billing_ref, subdomain, email, active, legal_entity, jurisdiction_country, jurisdiction_subdivision, address_line1, address_line2, address_city, address_region, address_postal_code, address_country, extra FROM sor.agent_accounts WHERE subdomain = $1
`

func (q *Queries) GetAgentAccountBySubdomain(ctx context.Context, subdomain string) (SorAgentAccount, error) {
	row := q.db.QueryRow(ctx, getAgentAccountBySubdomain, subdomain)
	var i SorAgentAccount
	err := row.Scan(
		&i.BillingRef,
		&i.Subdomain,
		&i.Email,
		&i.Active,
		&i.LegalEntity,
		&i.JurisdictionCountry,
		&i.JurisdictionSubdivision,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.AddressCity,
		&i.AddressRegion,
		&i.AddressPostalCode,
		&i.AddressCountry,
		&i.Extra,
	)
	return i, err
}

const insertAgentAccountIfAbsent = `-- name: InsertAgentAccountIfAbsent :one
INSERT INTO sor.agent_accounts (
    billing_ref, subdomain, email, active,
    legal_entity, jurisdiction_country, jurisdiction_subdivision,
    address_line1, address_line2, address_city, address_region,
    address_postal_code, address_country, extra
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
ON CONFLICT (subdomain) DO NOTHING
RETURNING billing_ref, subdomain, email, active, legal_entity, jurisdiction_country, jurisdiction_subdivision, address_line1, address_line2, address_city, address_region, address_postal_code, address_country, extra
`

type InsertAgentAccountIfAbsentParams struct {
	BillingRef              string      `json:"billing_ref"`
	Subdomain               string      `json:"subdomain"`
	Email                   pgtype.Text `json:"email"`
	Active                  bool        `json:"active"`
	LegalEntity             pgtype.Text `json:"legal_entity"`
	JurisdictionCountry     pgtype.Text `json:"jurisdiction_country"`
	JurisdictionSubdivision pgtype.Text `json:"jurisdiction_subdivision"`
	AddressLine1            pgtype.Text `json:"address_line1"`
	AddressLine2            pgtype.Text `json:"address_line2"`
	AddressCity             pgtype.Text `json:"address_city"`
	AddressRegion           pgtype.Text `json:"address_region"`
	AddressPostalCode       pgtype.Text `json:"address_postal_code"`
	AddressCountry          pgtype.Text `json:"address_country"`
	Extra                   []byte      `json:"extra"`
}

// Inserts a new account, or does NOTHING when one already exists for the
// subdomain (never DO UPDATE: a repeat registration must have zero side
// effects, per ADR-021 D4). When the conflict fires, RETURNING yields zero
// rows, so the caller sees pgx.ErrNoRows — the repo maps that to the
// "already exists" success signal, not an error.
func (q *Queries) InsertAgentAccountIfAbsent(ctx context.Context, arg InsertAgentAccountIfAbsentParams) (SorAgentAccount, error) {
	row := q.db.QueryRow(ctx, insertAgentAccountIfAbsent,
		arg.BillingRef,
		arg.Subdomain,
		arg.Email,
		arg.Active,
		arg.LegalEntity,
		arg.JurisdictionCountry,
		arg.JurisdictionSubdivision,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.AddressCity,
		arg.AddressRegion,
		arg.AddressPostalCode,
		arg.AddressCountry,
		arg.Extra,
	)
	var i SorAgentAccount
	err := row.Scan(
		&i.BillingRef,
		&i.Subdomain,
		&i.Email,
		&i.Active,
		&i.LegalEntity,
		&i.JurisdictionCountry,
		&i.JurisdictionSubdivision,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.AddressCity,
		&i.AddressRegion,
		&i.AddressPostalCode,
		&i.AddressCountry,
		&i.Extra,
	)
	return i, err
}
