// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SorAgentAccount struct {
	BillingRef              string      `json:"billing_ref"`
	Subdomain               string      `json:"subdomain"`
	Email                   pgtype.Text `json:"email"`
	Active                  bool        `json:"active"`
	LegalEntity             pgtype.Text `json:"legal_entity"`
	JurisdictionCountry     pgtype.Text `json:"jurisdiction_country"`
	JurisdictionSubdivision pgtype.Text `json:"jurisdiction_subdivision"`
	AddressLine1            pgtype.Text `json:"address_line1"`
	AddressLine2            pgtype.Text `json:"address_line2"`
	AddressCity             pgtype.Text `json:"address_city"`
	AddressRegion           pgtype.Text `json:"address_region"`
	AddressPostalCode       pgtype.Text `json:"address_postal_code"`
	AddressCountry          pgtype.Text `json:"address_country"`
	Extra                   []byte      `json:"extra"`
}
