// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	GetAgentAccountActive(ctx context.Context, billingRef string) (bool, error)
	GetAgentAccountBySubdomain(ctx context.Context, subdomain string) (SorAgentAccount, error)
	// Inserts a new account, or does NOTHING when one already exists for the
	// subdomain (never DO UPDATE: a repeat registration must have zero side
	// effects, per ADR-021 D4). When the conflict fires, RETURNING yields zero
	// rows, so the caller sees pgx.ErrNoRows — the repo maps that to the
	// "already exists" success signal, not an error.
	InsertAgentAccountIfAbsent(ctx context.Context, arg InsertAgentAccountIfAbsentParams) (SorAgentAccount, error)
}

var _ Querier = (*Queries)(nil)
