// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: card.sql

package sqlc

import (
	"context"
)

const getCardBySubdomain = `-- name: GetCardBySubdomain :one
SELECT subdomain, client_name, client_uri, contacts, purpose, created_at, updated_at
FROM identity.agent_card
WHERE subdomain = $1
`

func (q *Queries) GetCardBySubdomain(ctx context.Context, subdomain string) (IdentityAgentCard, error) {
	row := q.db.QueryRow(ctx, getCardBySubdomain, subdomain)
	var i IdentityAgentCard
	err := row.Scan(
		&i.Subdomain,
		&i.ClientName,
		&i.ClientUri,
		&i.Contacts,
		&i.Purpose,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCard = `-- name: UpsertCard :one
INSERT INTO identity.agent_card (subdomain, client_name, client_uri, contacts, purpose)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (subdomain) DO UPDATE SET
    client_name = EXCLUDED.client_name,
    client_uri  = EXCLUDED.client_uri,
    contacts    = EXCLUDED.contacts,
    purpose     = EXCLUDED.purpose,
    updated_at  = now()
RETURNING subdomain, client_name, client_uri, contacts, purpose, created_at, updated_at
`

type UpsertCardParams struct {
	Subdomain  string   `json:"subdomain"`
	ClientName string   `json:"client_name"`
	ClientUri  string   `json:"client_uri"`
	Contacts   []string `json:"contacts"`
	Purpose    string   `json:"purpose"`
}

func (q *Queries) UpsertCard(ctx context.Context, arg UpsertCardParams) (IdentityAgentCard, error) {
	row := q.db.QueryRow(ctx, upsertCard,
		arg.Subdomain,
		arg.ClientName,
		arg.ClientUri,
		arg.Contacts,
		arg.Purpose,
	)
	var i IdentityAgentCard
	err := row.Scan(
		&i.Subdomain,
		&i.ClientName,
		&i.ClientUri,
		&i.Contacts,
		&i.Purpose,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
