// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: developer.sql

package sqlc

import (
	"context"
)

const getDeveloperBySubdomain = `-- name: GetDeveloperBySubdomain :one
SELECT oidc_issuer, oidc_subject, email, subdomain, created_at FROM identity.developer_account
WHERE subdomain = $1
`

func (q *Queries) GetDeveloperBySubdomain(ctx context.Context, subdomain string) (IdentityDeveloperAccount, error) {
	row := q.db.QueryRow(ctx, getDeveloperBySubdomain, subdomain)
	var i IdentityDeveloperAccount
	err := row.Scan(
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.Email,
		&i.Subdomain,
		&i.CreatedAt,
	)
	return i, err
}

const getDeveloperBySubject = `-- name: GetDeveloperBySubject :one
SELECT oidc_issuer, oidc_subject, email, subdomain, created_at FROM identity.developer_account
WHERE oidc_issuer = $1 AND oidc_subject = $2
`

type GetDeveloperBySubjectParams struct {
	OidcIssuer  string `json:"oidc_issuer"`
	OidcSubject string `json:"oidc_subject"`
}

func (q *Queries) GetDeveloperBySubject(ctx context.Context, arg GetDeveloperBySubjectParams) (IdentityDeveloperAccount, error) {
	row := q.db.QueryRow(ctx, getDeveloperBySubject, arg.OidcIssuer, arg.OidcSubject)
	var i IdentityDeveloperAccount
	err := row.Scan(
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.Email,
		&i.Subdomain,
		&i.CreatedAt,
	)
	return i, err
}

const reserveDeveloper = `-- name: ReserveDeveloper :one
INSERT INTO identity.developer_account (oidc_issuer, oidc_subject, email, subdomain)
VALUES ($1, $2, $3, $4)
RETURNING oidc_issuer, oidc_subject, email, subdomain, created_at
`

type ReserveDeveloperParams struct {
	OidcIssuer  string `json:"oidc_issuer"`
	OidcSubject string `json:"oidc_subject"`
	Email       string `json:"email"`
	Subdomain   string `json:"subdomain"`
}

func (q *Queries) ReserveDeveloper(ctx context.Context, arg ReserveDeveloperParams) (IdentityDeveloperAccount, error) {
	row := q.db.QueryRow(ctx, reserveDeveloper,
		arg.OidcIssuer,
		arg.OidcSubject,
		arg.Email,
		arg.Subdomain,
	)
	var i IdentityDeveloperAccount
	err := row.Scan(
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.Email,
		&i.Subdomain,
		&i.CreatedAt,
	)
	return i, err
}
