// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exchange_registration.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const forgetExchangeRegistration = `-- name: ForgetExchangeRegistration :exec
DELETE FROM identity.exchange_registration
WHERE subdomain = $1 AND exchange = $2
`

type ForgetExchangeRegistrationParams struct {
	Subdomain string `json:"subdomain"`
	Exchange  string `json:"exchange"`
}

func (q *Queries) ForgetExchangeRegistration(ctx context.Context, arg ForgetExchangeRegistrationParams) error {
	_, err := q.db.Exec(ctx, forgetExchangeRegistration, arg.Subdomain, arg.Exchange)
	return err
}

const listExchangeRegistrations = `-- name: ListExchangeRegistrations :many
SELECT exchange, registered_at FROM identity.exchange_registration
WHERE subdomain = $1
ORDER BY exchange
LIMIT $2::int
`

type ListExchangeRegistrationsParams struct {
	Subdomain string `json:"subdomain"`
	MaxNotes  int32  `json:"max_notes"`
}

type ListExchangeRegistrationsRow struct {
	Exchange     string             `json:"exchange"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
}

// Ordered by domain because that is how the list is presented, and capped by the
// same number the write path enforces.
//
// The cap is a backstop rather than the bound: RecordExchangeRegistration keeps
// the set at or under it, so this LIMIT never truncates a set that path produced.
// It is here so the read cannot become unbounded if rows ever arrive by another
// route.
func (q *Queries) ListExchangeRegistrations(ctx context.Context, arg ListExchangeRegistrationsParams) ([]ListExchangeRegistrationsRow, error) {
	rows, err := q.db.Query(ctx, listExchangeRegistrations, arg.Subdomain, arg.MaxNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExchangeRegistrationsRow{}
	for rows.Next() {
		var i ListExchangeRegistrationsRow
		if err := rows.Scan(&i.Exchange, &i.RegisteredAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordExchangeRegistration = `-- name: RecordExchangeRegistration :exec
WITH upserted AS (
    INSERT INTO identity.exchange_registration (subdomain, exchange, registered_at)
    VALUES ($1, $2, $3)
    ON CONFLICT (subdomain, exchange) DO UPDATE SET registered_at = EXCLUDED.registered_at
), keep AS (
    SELECT exchange FROM identity.exchange_registration
    WHERE subdomain = $1 AND exchange <> $2
    ORDER BY registered_at DESC, exchange
    LIMIT $4::int
)
DELETE FROM identity.exchange_registration AS note
WHERE note.subdomain = $1
  AND note.exchange <> $2
  AND note.exchange NOT IN (SELECT keep.exchange FROM keep)
`

type RecordExchangeRegistrationParams struct {
	Subdomain    string             `json:"subdomain"`
	Exchange     string             `json:"exchange"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
	KeepOthers   int32              `json:"keep_others"`
}

// Writes the note and, in the same statement, drops this agent's oldest notes
// past the cap.
//
// The exchange is a value an authenticated agent chooses per call, and with no
// allowlist configured the key space is the whole DNS namespace. So the note set
// is somewhere a caller can make this table grow, and it is bounded the same way
// every caller-influenced store in this service is: keep the most recent, drop
// the rest.
//
// One statement, so there is no read-then-write to make atomic. The two halves
// need care about visibility: a data-modifying CTE runs against the snapshot
// taken at the start of the statement, so the DELETE cannot see the row the
// INSERT just wrote. That is why `keep` selects the cap MINUS ONE most recent
// OTHER notes and the DELETE excludes this exchange outright — the row being
// written is kept by construction rather than by being found.
func (q *Queries) RecordExchangeRegistration(ctx context.Context, arg RecordExchangeRegistrationParams) error {
	_, err := q.db.Exec(ctx, recordExchangeRegistration,
		arg.Subdomain,
		arg.Exchange,
		arg.RegisteredAt,
		arg.KeepOthers,
	)
	return err
}
