// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IdentityAgentCard struct {
	Subdomain  string             `json:"subdomain"`
	ClientName string             `json:"client_name"`
	ClientUri  string             `json:"client_uri"`
	Contacts   []string           `json:"contacts"`
	Purpose    string             `json:"purpose"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type IdentityDeveloperAccount struct {
	OidcIssuer  string             `json:"oidc_issuer"`
	OidcSubject string             `json:"oidc_subject"`
	Email       string             `json:"email"`
	Subdomain   string             `json:"subdomain"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type IdentityExchangeRegistration struct {
	Subdomain    string             `json:"subdomain"`
	Exchange     string             `json:"exchange"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
}

type IdentityKeyRevocation struct {
	Subdomain string   `json:"subdomain"`
	AsOf      int64    `json:"as_of"`
	Revoked   []string `json:"revoked"`
}

type IdentityOauthAuthzCode struct {
	CodeHash      string             `json:"code_hash"`
	ClientID      string             `json:"client_id"`
	RedirectUri   string             `json:"redirect_uri"`
	PkceChallenge string             `json:"pkce_challenge"`
	Subject       string             `json:"subject"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	Consumed      bool               `json:"consumed"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type IdentityOauthClient struct {
	ClientID     string             `json:"client_id"`
	RedirectUris []string           `json:"redirect_uris"`
	ClientName   string             `json:"client_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
