// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeAuthzCode = `-- name: ConsumeAuthzCode :one
UPDATE identity.oauth_authz_code
SET consumed = true
WHERE code_hash = $1 AND NOT consumed
RETURNING code_hash, client_id, redirect_uri, pkce_challenge, subject, expires_at, consumed, created_at
`

// Single-use redemption: flips consumed atomically and returns the row only on the
// first redemption. A second attempt matches no row (NOT consumed is false) and
// yields pgx.ErrNoRows. Expiry is returned, not enforced here, so the caller checks
// it against the same clock that minted expires_at.
func (q *Queries) ConsumeAuthzCode(ctx context.Context, codeHash string) (IdentityOauthAuthzCode, error) {
	row := q.db.QueryRow(ctx, consumeAuthzCode, codeHash)
	var i IdentityOauthAuthzCode
	err := row.Scan(
		&i.CodeHash,
		&i.ClientID,
		&i.RedirectUri,
		&i.PkceChallenge,
		&i.Subject,
		&i.ExpiresAt,
		&i.Consumed,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthzCode = `-- name: GetAuthzCode :one
SELECT code_hash, client_id, redirect_uri, pkce_challenge, subject, expires_at, consumed, created_at FROM identity.oauth_authz_code
WHERE code_hash = $1
`

// Peek at a code without consuming it, so /token can validate every binding
// (expiry, client_id, redirect_uri, PKCE) BEFORE it burns the code. A row is
// returned whether or not it is already consumed; an unknown code yields
// pgx.ErrNoRows. The atomic burn is ConsumeAuthzCode, run only once validation
// passes — so a stolen code presented with a wrong verifier cannot spend the
// legitimate client's code.
func (q *Queries) GetAuthzCode(ctx context.Context, codeHash string) (IdentityOauthAuthzCode, error) {
	row := q.db.QueryRow(ctx, getAuthzCode, codeHash)
	var i IdentityOauthAuthzCode
	err := row.Scan(
		&i.CodeHash,
		&i.ClientID,
		&i.RedirectUri,
		&i.PkceChallenge,
		&i.Subject,
		&i.ExpiresAt,
		&i.Consumed,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthClient = `-- name: GetOAuthClient :one
SELECT client_id, redirect_uris, client_name, created_at FROM identity.oauth_client
WHERE client_id = $1
`

func (q *Queries) GetOAuthClient(ctx context.Context, clientID string) (IdentityOauthClient, error) {
	row := q.db.QueryRow(ctx, getOAuthClient, clientID)
	var i IdentityOauthClient
	err := row.Scan(
		&i.ClientID,
		&i.RedirectUris,
		&i.ClientName,
		&i.CreatedAt,
	)
	return i, err
}

const issueAuthzCode = `-- name: IssueAuthzCode :one
INSERT INTO identity.oauth_authz_code (
    code_hash, client_id, redirect_uri, pkce_challenge, subject, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING code_hash, client_id, redirect_uri, pkce_challenge, subject, expires_at, consumed, created_at
`

type IssueAuthzCodeParams struct {
	CodeHash      string             `json:"code_hash"`
	ClientID      string             `json:"client_id"`
	RedirectUri   string             `json:"redirect_uri"`
	PkceChallenge string             `json:"pkce_challenge"`
	Subject       string             `json:"subject"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) IssueAuthzCode(ctx context.Context, arg IssueAuthzCodeParams) (IdentityOauthAuthzCode, error) {
	row := q.db.QueryRow(ctx, issueAuthzCode,
		arg.CodeHash,
		arg.ClientID,
		arg.RedirectUri,
		arg.PkceChallenge,
		arg.Subject,
		arg.ExpiresAt,
	)
	var i IdentityOauthAuthzCode
	err := row.Scan(
		&i.CodeHash,
		&i.ClientID,
		&i.RedirectUri,
		&i.PkceChallenge,
		&i.Subject,
		&i.ExpiresAt,
		&i.Consumed,
		&i.CreatedAt,
	)
	return i, err
}

const registerOAuthClient = `-- name: RegisterOAuthClient :one
INSERT INTO identity.oauth_client (client_id, redirect_uris, client_name)
VALUES ($1, $2, $3)
RETURNING client_id, redirect_uris, client_name, created_at
`

type RegisterOAuthClientParams struct {
	ClientID     string   `json:"client_id"`
	RedirectUris []string `json:"redirect_uris"`
	ClientName   string   `json:"client_name"`
}

func (q *Queries) RegisterOAuthClient(ctx context.Context, arg RegisterOAuthClientParams) (IdentityOauthClient, error) {
	row := q.db.QueryRow(ctx, registerOAuthClient, arg.ClientID, arg.RedirectUris, arg.ClientName)
	var i IdentityOauthClient
	err := row.Scan(
		&i.ClientID,
		&i.RedirectUris,
		&i.ClientName,
		&i.CreatedAt,
	)
	return i, err
}
