// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CompleteDeveloperRegistration(ctx context.Context, arg CompleteDeveloperRegistrationParams) (IdentityDeveloperAccount, error)
	// Single-use redemption: flips consumed atomically and returns the row only on the
	// first redemption. A second attempt matches no row (NOT consumed is false) and
	// yields pgx.ErrNoRows. Expiry is returned, not enforced here, so the caller checks
	// it against the same clock that minted expires_at.
	ConsumeAuthzCode(ctx context.Context, codeHash string) (IdentityOauthAuthzCode, error)
	// Peek at a code without consuming it, so /token can validate every binding
	// (expiry, client_id, redirect_uri, PKCE) BEFORE it burns the code. A row is
	// returned whether or not it is already consumed; an unknown code yields
	// pgx.ErrNoRows. The atomic burn is ConsumeAuthzCode, run only once validation
	// passes — so a stolen code presented with a wrong verifier cannot spend the
	// legitimate client's code.
	GetAuthzCode(ctx context.Context, codeHash string) (IdentityOauthAuthzCode, error)
	GetCardBySubdomain(ctx context.Context, subdomain string) (IdentityAgentCard, error)
	GetDeveloperBySubdomain(ctx context.Context, subdomain string) (IdentityDeveloperAccount, error)
	GetDeveloperBySubject(ctx context.Context, arg GetDeveloperBySubjectParams) (IdentityDeveloperAccount, error)
	GetOAuthClient(ctx context.Context, clientID string) (IdentityOauthClient, error)
	GetRevocation(ctx context.Context, subdomain string) (GetRevocationRow, error)
	IssueAuthzCode(ctx context.Context, arg IssueAuthzCodeParams) (IdentityOauthAuthzCode, error)
	RegisterOAuthClient(ctx context.Context, arg RegisterOAuthClientParams) (IdentityOauthClient, error)
	ReserveDeveloper(ctx context.Context, arg ReserveDeveloperParams) (IdentityDeveloperAccount, error)
	// Append thumbprint to the subdomain's revoked set and advance as_of to a value
	// strictly greater than both its previous value and now_epoch, so every published
	// snapshot carries a strictly-increasing as_of even if two revokes land in the same
	// clock tick or the clock steps backward. A thumbprint already present is not
	// duplicated, but the publication still bumps as_of.
	Revoke(ctx context.Context, arg RevokeParams) (int64, error)
	UpsertCard(ctx context.Context, arg UpsertCardParams) (IdentityAgentCard, error)
}

var _ Querier = (*Queries)(nil)
