// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: revocation.sql

package sqlc

import (
	"context"
)

const getRevocation = `-- name: GetRevocation :one
SELECT as_of, revoked
FROM identity.key_revocation
WHERE subdomain = $1
`

type GetRevocationRow struct {
	AsOf    int64    `json:"as_of"`
	Revoked []string `json:"revoked"`
}

func (q *Queries) GetRevocation(ctx context.Context, subdomain string) (GetRevocationRow, error) {
	row := q.db.QueryRow(ctx, getRevocation, subdomain)
	var i GetRevocationRow
	err := row.Scan(&i.AsOf, &i.Revoked)
	return i, err
}

const revoke = `-- name: Revoke :one
INSERT INTO identity.key_revocation (subdomain, as_of, revoked)
VALUES ($1, $2, ARRAY[$3::text])
ON CONFLICT (subdomain) DO UPDATE SET
    as_of = GREATEST(identity.key_revocation.as_of + 1, $2),
    revoked = CASE
        WHEN $3 = ANY (identity.key_revocation.revoked)
            THEN identity.key_revocation.revoked
        ELSE array_append(identity.key_revocation.revoked, $3)
    END
RETURNING as_of
`

type RevokeParams struct {
	Subdomain  string `json:"subdomain"`
	NowEpoch   int64  `json:"now_epoch"`
	Thumbprint string `json:"thumbprint"`
}

// Append thumbprint to the subdomain's revoked set and advance as_of to a value
// strictly greater than both its previous value and now_epoch, so every published
// snapshot carries a strictly-increasing as_of even if two revokes land in the same
// clock tick or the clock steps backward. A thumbprint already present is not
// duplicated, but the publication still bumps as_of.
func (q *Queries) Revoke(ctx context.Context, arg RevokeParams) (int64, error) {
	row := q.db.QueryRow(ctx, revoke, arg.Subdomain, arg.NowEpoch, arg.Thumbprint)
	var as_of int64
	err := row.Scan(&as_of)
	return as_of, err
}
