"""Test-harness signing helper for the v1 obligation tests.

Why this exists
---------------
Post-commit 9c3a93b, the Exchange's RFC 9421 httpsig
middleware verifies every ``/ramp.v1.ExchangeService/*`` and
``/ramp.v1.BrokerService/*`` request unconditionally. The previous
"sign only when ``Signature-Input`` is present" predicate let plain
``httpx.post()`` calls fall through to the service layer; the new
predicate refuses them at the transport layer with Connect
``unauthenticated``.

The obligation tests under ``tests/e2e/harness/obligations/`` exercise
agent-direct surfaces — ``DiscoverResources``, ``ExecuteTransaction``,
``ReportUsage`` — and used to drive them with bare ``httpx.post()``.
Each such call now needs an RFC 9421 signature stamped on the request
with a ``kid`` the Exchange's key resolver can resolve.

There is no static key file: the Exchange learns a signer's key by
fetching the WBA directory named by the request's covered
``Signature-Agent`` header (which this signer sets to the kid). In the
compose stack each identity's directory is served by its own jwks host
aliased to the kid — the test signer's key (``kid="test-signer-e2e.v1"``)
is served by the ``test-signer-e2e.v1-jwks`` service; the private half lives at
``tests/e2e/harness/fixtures/test_signer_key.json`` (generated by
``scripts/gen-e2e-keys.sh``, gitignored).

Test signer identity vs. catalog contributor identity
-----------------------------------------------------
The catalog contributor key (``catalog-contributor-e2e``, see
``catalog_push.py``) signs ``CatalogService/PushResources``; its
verifier reads from ``ramp.agents`` (Gate 1) plus the publisher's
``ramp.json`` (Gate 2). The two identities stay separate so the
contributor key keeps its narrow catalog-write scope.

The test signer is a *different* identity used only by the obligation
tests for their agent-direct ``ExchangeService`` calls. Its ``kid`` is
prefixed ``test-`` so production graders can tell at a glance that a
``test-signer-*`` signature has no business appearing in a non-test
trace.

Decoupling kid from requester.id
--------------------------------
RFC 9421's ``keyid`` parameter identifies the signing key. The Exchange's
service layer (``exchange.go::DiscoverResources``) separately requires a
non-empty ``requester.id`` in the request body — that's the *agent*
identity attached to the audit trail. The two are decoupled by design: a
single test signer ``kid`` can carry requests on behalf of many different
``agent_id`` values, and the service layer never reads the ``kid`` to
infer who the caller is.

Public surface
--------------
:func:`sign_post` — POST a JSON body to a ``/ramp.*`` URL, signing the
request with the test signer key. Returns ``httpx.Response``.

:func:`build_signed_headers` — build the four RFC 9421 headers without
issuing a request. Useful for tests that need to inspect or mutate the
headers before sending.
"""

from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Any

import httpx
from ramp_sdk.pop import sign_agent_binding

from .httpsig_signer import load_keypair, sign_request

# Path to the generated test signer key fixture (scripts/gen-e2e-keys.sh,
# gitignored). Resolved relative to this module so the fixture follows the
# harness whether the runner is the repo checkout, the in-network compose
# `runner` service, or a CI image that COPYs the harness tree intact.
TEST_SIGNER_KEY_PATH = Path(__file__).resolve().parent / "fixtures" / "test_signer_key.json"

# Re-export agent key fixtures that now live in seed.py, for harness modules and
# tests that historically import them from `.signing` (v1.1 merge reconciliation;
# seed has no dependency back on signing, so this is cycle-safe). The demo terms
# are denominated in EUR/USD; the in-memory billing adapter authorizes a term
# only on a currency match, so EUR terms are bought with the EUR buyer
# and USD terms with the USD buyer (== agent-e2e).
from .seed import (  # noqa: E402,F401
    EUR_AGENT_KEY_PATH,
    USD_AGENT_ID,
    USD_AGENT_KEY_PATH,
)

# Agent identities the obligation/full-stack tests act AS. Their kid equals the
# agent_id and is registered in ramp.agents by seed.py, so the Exchange's
# caller authz (resolveCaller + authorizeForAgent: kid == requester.id)
# admits them on ExecuteTransaction / ReportUsage. Distinct from the generic
# test signer above, which is a transport-only kid NOT in ramp.agents (used by
# the obligation-05 httpsig negatives that never reach the caller-authz layer).
AGENT_E2E_KEY_PATH = Path(__file__).resolve().parent / "fixtures" / "agent_e2e_key.json"
AGENT_NOBILLING_KEY_PATH = (
    Path(__file__).resolve().parent / "fixtures" / "agent_nobilling_e2e_key.json"
)

# Proof-of-possession signature TTL (seconds) for bound signed-URL GETs (ADR-013).
_DEFAULT_TTL_SECONDS = 30

# Caller-supplied header carrying the target Exchange endpoint for the known-URL
# relay. The Go consumer names it via the ``headerExchangeEndpoint`` constant
# (src/broker/internal/transport/exchange_relay.go); a single Python constant
# keeps every harness producer in sync. The string MUST match the Go
# side byte-for-byte — it crosses the Python→Go boundary, so the two can't share
# one literal.
EXCHANGE_ENDPOINT_HEADER = "X-RAMP-Exchange-Endpoint"


def build_signed_headers(
    *,
    method: str,
    target_uri: str,
    body: bytes,
    content_type: str = "application/json",
    key_path: Path | None = None,
) -> dict[str, str]:
    """Build the four RFC 9421 headers + Content-Type for a request.

    By default the generic test signer (``TEST_SIGNER_KEY_PATH``) signs;
    pass ``key_path`` to sign AS a registered agent (e.g.
    ``AGENT_E2E_KEY_PATH``). Tests that want a fully custom/invalid kid
    (e.g. the obligation-05 "unknown signer" scenarios) build their own
    headers via ``httpsig_signer``.
    """
    # sign_request is the single WBA signer: keyid = RFC 7638 thumbprint and the
    # covered Signature-Agent defaults to kid (in the demo/tests an agent's kid ==
    # its directory == caller identity). Content-Type is not part of the signing
    # base, so it is added to the returned headers here.
    kid, priv = load_keypair(key_path or TEST_SIGNER_KEY_PATH)
    signed = sign_request(method=method, target_uri=target_uri, body=body, kid=kid, priv=priv)
    return {**signed.headers, "Content-Type": content_type}


def sign_post(
    url: str,
    *,
    body: dict[str, Any],
    timeout: float = 30.0,
    extra_headers: dict[str, str] | None = None,
    key_path: Path | None = None,
) -> httpx.Response:
    """POST ``body`` (as JSON) to ``url`` with an RFC 9421 signature.

    ``body`` is serialised to JSON with the same canonicalisation the
    server applies (no spaces, sorted-key-free). The Content-Digest
    header commits to the exact bytes sent, so callers must NOT mutate
    the body after this call returns.

    ``key_path`` selects the signing identity (default: generic test
    signer). Agent-direct surfaces (ExecuteTransaction / ReportUsage)
    MUST pass ``AGENT_E2E_KEY_PATH`` or ``AGENT_NOBILLING_KEY_PATH`` so
    the signing kid equals ``requester.id``.

    ``extra_headers`` are merged AFTER the signed headers, allowing
    callers to add observability stubs (e.g. ``X-RAMP-Agent-Id``) that
    are not part of the signing base. The four signed headers and
    Content-Type cannot be overridden — the signer's commitment is
    cryptographic and the verifier compares the wire bytes.
    """
    payload = json.dumps(body, separators=(",", ":")).encode()
    headers = build_signed_headers(method="POST", target_uri=url, body=payload, key_path=key_path)
    if extra_headers:
        for key, value in extra_headers.items():
            if key in {
                "Content-Digest",
                "Authorization",
                "Signature-Agent",
                "Signature-Input",
                "Signature",
            }:
                msg = f"sign_post: caller may not override signed header {key!r}"
                raise ValueError(msg)
            headers[key] = value
    return httpx.post(url, content=payload, headers=headers, timeout=timeout)


def build_pop_headers(
    *,
    url: str,
    key_path: Path = AGENT_E2E_KEY_PATH,
) -> dict[str, str]:
    """Build proof-of-possession headers for fetching a bound signed URL (ADR-013).

    When a signed URL carries an agent_id (the agent's RFC 7638 thumbprint),
    the edge requires proof of possession: the fetcher must present its raw
    Ed25519 public key (X-RAMP-Agent-Key) and sign the GET with RFC 9421
    over @method + @target-uri. The edge enforces 3-way identity:

        agent_id (URL param) == keyid (Signature-Input) == thumbprint(presented key)

    Args:
        url: Full signed URL to fetch (the @target-uri value)
        key_path: Agent key file (default: agent-e2e)

    Returns:
        Headers dict with X-RAMP-Agent-Key, Signature-Input, Signature
    """
    _kid, priv = load_keypair(key_path)

    # The SDK's PoP SIGN face owns the covered set, keyid derivation, and the
    # vector-pinned signature base; the harness supplies only the key and clock.
    created = int(time.time())
    presented_key, signature_input, signature = sign_agent_binding(
        url=url,
        signer_seed=priv.private_bytes_raw(),
        created=created,
        expires=created + _DEFAULT_TTL_SECONDS,
    )
    return {
        "X-RAMP-Agent-Key": presented_key,
        "Signature-Input": signature_input,
        "Signature": signature,
    }


__all__ = [
    "AGENT_E2E_KEY_PATH",
    "AGENT_NOBILLING_KEY_PATH",
    "EUR_AGENT_KEY_PATH",
    "TEST_SIGNER_KEY_PATH",
    "USD_AGENT_KEY_PATH",
    "build_signed_headers",
    "build_pop_headers",
    "sign_post",
]
