# All-inclusive RAMP demo on AWS: one EC2 VM running the Compose stack
# (Postgres, Redis, TigerBeetle, Exchange, Broker, the Identity Service with
# its Vault and Zitadel, Caddy, demo origin), Route 53 records for the service
# hostnames, and a CloudFront distribution whose viewer-request Lambda@Edge
# function runs the SAME Ed25519 edge worker the Cloudflare deployments run —
# for a domain whose DNS stays in Route 53.
#
# Every hostname nests under one label (demo.<domain> and its children), so
# the whole deployment adds records to a shared zone without touching anything
# else in it.
#
# Key material under keys/ comes from ../../scripts/gen-staging-keys.sh (run
# with STACK_DIR pointing at this directory). The Lambda bundle is built by
# ../../scripts/build-lambda-edge.sh from the config this stack renders — see
# the lambda_edge_config output and the deploy_edge variable for the
# bootstrap order.

locals {
  publisher_fqdn = "${var.publisher_subdomain}.${var.domain}"

  # Zone-relative record names ("exchange.demo") and full hostnames
  # ("exchange.demo.<domain>") for the five service names under the publisher
  # label.
  exchange_record = "${var.exchange_subdomain}.${var.publisher_subdomain}"
  broker_record   = "${var.broker_subdomain}.${var.publisher_subdomain}"
  identity_record = "${var.identity_subdomain}.${var.publisher_subdomain}"
  zitadel_record  = "${var.zitadel_subdomain}.${var.publisher_subdomain}"
  origin_record   = "${var.origin_subdomain}.${var.publisher_subdomain}"

  exchange_fqdn = "${local.exchange_record}.${var.domain}"
  broker_fqdn   = "${local.broker_record}.${var.domain}"
  identity_fqdn = "${local.identity_record}.${var.domain}"
  zitadel_fqdn  = "${local.zitadel_record}.${var.domain}"
  origin_fqdn   = "${local.origin_record}.${var.domain}"

  # The smoke identities: each hostname IS the identity's id (its kid, its
  # ramp.agents row, and the host its public key directory is served at).
  # They nest under the publisher label like every other name in this stack,
  # so the id the key-gen script derives on a first run must be
  # <label>.<publisher_subdomain>.<domain> — set STAGING_DOMAIN to the
  # publisher hostname (demo.<domain>), not the zone apex.
  smoke_agent_record         = "${var.smoke_agent_subdomain}.${var.publisher_subdomain}"
  catalog_contributor_record = "${var.catalog_contributor_subdomain}.${var.publisher_subdomain}"
  smoke_agent_fqdn           = "${local.smoke_agent_record}.${var.domain}"
  catalog_contributor_fqdn   = "${local.catalog_contributor_record}.${var.domain}"

  image_base      = "${var.image_registry}/${var.image_prefix}"
  exchange_image  = "${local.image_base}/exchange:${var.image_tag}"
  broker_image    = "${local.image_base}/broker:${var.image_tag}"
  identity_image  = "${local.image_base}/identity:${var.image_tag}"
  publisher_image = "${local.image_base}/publisher:${var.image_tag}"

  # Default to the in-repo bundle location: build-lambda-edge.sh writes it
  # there, and when the bundle is missing the module's fileexists validation
  # fails the plan with a message pointing at the build script instead of
  # failing obscurely.
  lambda_zip_path = coalesce(var.lambda_zip_path, "${path.module}/../../../../src/edge/dist/lambda-edge.zip")

  # Key material generated by gen-staging-keys.sh into the gitignored keys/
  # directory next to this stack (run it with STACK_DIR set to this
  # directory). agent-key.json and contributor-key.json are written by the
  # same script but stay local — no service on the VM needs them.
  keys_dir = "${path.root}/keys"
  # Optional: the Exchange only needs it for AWS_CLOUDFRONT_RSA tenants, which
  # the demo has none of — the CloudFront distribution here does NOT use
  # CloudFront's native RSA signed URLs (Ed25519 verification runs inside the
  # Lambda). gen-staging-keys.sh writes one anyway; deleting it is a supported
  # posture.
  rsa_private_pem = fileexists("${local.keys_dir}/rsa-private.pem") ? file("${local.keys_dir}/rsa-private.pem") : null

  # The per-deployment config baked into the Lambda bundle, rendered HERE so
  # the bundle and the stack can never disagree on a hostname. The operator
  # writes it to a file (terraform output -raw lambda_edge_config) and feeds
  # it to build-lambda-edge.sh. Lambda@Edge has no environment variables, so
  # unlike the cloudflare-edge module these values travel inside the zip.
  #
  # ORIGIN_URL and SAME_ZONE_ORIGIN are deliberately ABSENT: with no origin
  # mode the shared worker answers an authorized request with the pass-through
  # marker, the AWS entry returns the CloudFront request object, and
  # CloudFront itself fetches the origin (origin.demo.<domain>) configured on
  # the distribution. The Lambda never proxies article bodies.
  lambda_edge_config = merge(
    {
      EXCHANGE_URL              = "https://${local.exchange_fqdn}"
      EXCHANGE_WBA_URL          = "https://${local.exchange_fqdn}/.well-known/http-message-signatures-directory"
      PROVIDER                  = local.publisher_fqdn
      EXCHANGES_JSON            = module.manifest.exchanges_json
      CATALOG_CONTRIBUTORS_JSON = module.manifest.catalog_contributors_json
    },
    var.ramp_enforce_binding == null ? {} : { RAMP_ENFORCE_BINDING = var.ramp_enforce_binding },
  )
}

# Resource-free, so it is always evaluated — including the bootstrap apply
# with deploy_edge = false, where the rendered config must exist before the
# bundle (and therefore before module.edge) can.
module "manifest" {
  source = "../../modules/publisher-manifest"

  exchange_fqdn     = local.exchange_fqdn
  resource_owner_id = var.resource_owner_id
  # The contributor id IS the hostname its key directory is served at (the
  # smoke identity hostname derived above) — there is no separate id variable.
  catalog_contributor_id = local.catalog_contributor_fqdn
}

module "compose_stack" {
  source = "../../modules/compose-stack"

  exchange_hostname = local.exchange_fqdn
  broker_hostname   = local.broker_fqdn
  identity_hostname = local.identity_fqdn
  zitadel_hostname  = local.zitadel_fqdn
  origin_hostname   = local.origin_fqdn

  exchange_image  = local.exchange_image
  broker_image    = local.broker_image
  identity_image  = local.identity_image
  publisher_image = local.publisher_image

  registry_server   = var.registry_username == null ? null : var.image_registry
  registry_username = var.registry_username
  registry_password = var.registry_password

  billing_adapter = var.billing_adapter
  acme_email      = var.acme_email
  acme_staging    = var.acme_staging
  exa_api_key     = var.exa_api_key

  default_tenant_domain = local.publisher_fqdn

  # There is no keys.json / static key file: every verification key is
  # learned via well-known discovery — the Broker publishes its own keys, an
  # agent's key is fetched from the agent's own directory, and the smoke
  # identities' directories are served by this stack below.
  ed25519_private_pem     = file("${local.keys_dir}/ed25519-private.pem")
  rsa_private_pem         = local.rsa_private_pem
  broker_relay_key_json   = file("${local.keys_dir}/broker-relay-key.json")
  broker_identity_key_pem = file("${local.keys_dir}/broker-identity-key.pem")

  # PUBLIC key directories for the smoke identities (gen-staging-keys.sh
  # derives them from the local keypairs — the private halves never leave the
  # operator's machine). Caddy serves each at its identity's hostname, which is
  # how the Exchange and Broker verify the smoke and ingest signatures.
  static_wba_directories = {
    (local.smoke_agent_fqdn)         = file("${local.keys_dir}/smoke-agent-wba.json")
    (local.catalog_contributor_fqdn) = file("${local.keys_dir}/catalog-contributor-wba.json")
  }
}

module "vm" {
  source = "../../modules/aws-vm"

  name_prefix      = var.name_prefix
  instance_type    = var.instance_type
  ssh_public_key   = var.ssh_public_key
  ssh_ingress_cidr = var.ssh_ingress_cidr
  user_data        = module.compose_stack.user_data
}

module "dns" {
  source = "../../modules/route53-dns"

  zone_id = var.route53_zone_id
  a_records = {
    (local.exchange_record) = module.vm.public_ip
    (local.broker_record)   = module.vm.public_ip
    (local.identity_record) = module.vm.public_ip
    (local.zitadel_record)  = module.vm.public_ip
    (local.origin_record)   = module.vm.public_ip
    # The smoke identities' key directory hostnames — Caddy serves each
    # identity's public JWK Set there (static_wba_directories above).
    (local.smoke_agent_record)         = module.vm.public_ip
    (local.catalog_contributor_record) = module.vm.public_ip
    # Agent Web Bot Auth directories: one hostname per agent, created by a
    # developer signing up rather than by Terraform, so the record has to be a
    # wildcard. Caddy mints each subdomain's certificate on demand.
    ("*.${local.identity_record}") = module.vm.public_ip
  }

  # The publisher hostname aliases the CloudFront distribution (A + AAAA).
  # Only when the edge is deployed — during bootstrap (deploy_edge = false)
  # the name stays unclaimed rather than pointing anywhere wrong.
  alias_records = var.deploy_edge ? {
    (var.publisher_subdomain) = {
      target_domain  = module.edge[0].distribution_domain_name
      target_zone_id = module.edge[0].distribution_hosted_zone_id
    }
  } : {}
}

module "edge" {
  count  = var.deploy_edge ? 1 : 0
  source = "../../modules/aws-cloudfront-edge"

  # Lambda@Edge and the CloudFront certificate must live in us-east-1
  # regardless of the VM's region.
  providers = { aws = aws.us_east_1 }

  name_prefix     = var.name_prefix
  lambda_zip_path = local.lambda_zip_path
  hostname        = local.publisher_fqdn
  zone_id         = var.route53_zone_id
  origin_domain   = local.origin_fqdn
}
