# All-inclusive RAMP staging: one EC2 VM running the Compose stack (Postgres,
# Redis, TigerBeetle, Exchange, Broker, the Identity Service with its Vault and
# Zitadel, Caddy, demo origin), Cloudflare DNS for the service hostnames, and
# the Cloudflare edge worker fronting the demo publisher hostname — the same
# surface a publisher's production deployment runs.
#
# Deploy order and how to update a running environment: ../../docs/deploy-staging-aws.md.
# Key material under keys/ comes from ../../scripts/gen-staging-keys.sh.

locals {
  exchange_fqdn  = "${var.exchange_subdomain}.${var.domain}"
  broker_fqdn    = "${var.broker_subdomain}.${var.domain}"
  identity_fqdn  = "${var.identity_subdomain}.${var.domain}"
  zitadel_fqdn   = "${var.zitadel_subdomain}.${var.domain}"
  origin_fqdn    = "${var.origin_subdomain}.${var.domain}"
  publisher_fqdn = "${var.publisher_subdomain}.${var.domain}"
  # The smoke identities: each hostname IS the identity's id (its kid, its
  # ramp.agents row, and the host its public key directory is served at).
  smoke_agent_fqdn         = "${var.smoke_agent_subdomain}.${var.domain}"
  catalog_contributor_fqdn = "${var.catalog_contributor_subdomain}.${var.domain}"

  image_base      = "${var.image_registry}/${var.image_prefix}"
  exchange_image  = "${local.image_base}/exchange:${var.image_tag}"
  broker_image    = "${local.image_base}/broker:${var.image_tag}"
  identity_image  = "${local.image_base}/identity:${var.image_tag}"
  publisher_image = "${local.image_base}/publisher:${var.image_tag}"

  # Default to the in-repo bundle location (same shape as stacks/edge): the
  # repo checkout is where build-cloudflare-edge.sh writes it, and when the
  # bundle is missing the module's fileexists validation fails the plan with
  # a message pointing at the build script instead of failing obscurely.
  worker_bundle_path = coalesce(var.worker_bundle_path, "${path.module}/../../../../src/edge/dist/worker.mjs")

  # Key material generated by gen-staging-keys.sh into the gitignored keys/
  # directory next to this stack. rsa-private.pem is optional (see below); the
  # rest is mandatory and terraform errors loudly if missing. agent-key.json is
  # written by the same script but stays local — the smoke test signs Broker
  # calls with it directly and no service on the VM needs it.
  #
  # Two of these are Broker keys and they are not interchangeable:
  # broker-relay-key.json signs Broker->Exchange calls (the Broker publishes
  # its pubkey in its own WBA directory, where the Exchange resolves it), while
  # broker-identity-key.pem is the identity key that same directory is signed
  # under. Both must be stable across restarts and VM recreates, which is why
  # they live here rather than being minted on the VM.
  keys_dir = "${path.root}/keys"
  # Optional: the Exchange only needs it for AWS_CLOUDFRONT_RSA tenants, which
  # staging has none of. gen-staging-keys.sh writes one anyway, so it is normally
  # present and gets picked up; deleting it is a supported posture.
  rsa_private_pem = fileexists("${local.keys_dir}/rsa-private.pem") ? file("${local.keys_dir}/rsa-private.pem") : null

  # The seed step creates the tenant under the publisher hostname, so that is
  # the domain Register must look up. Overridable for the deploy_edge = false
  # mode, where a client publisher's hostname is seeded instead. A local (not
  # an inline module argument) because the default_tenant_domain output
  # exports the same derived value for seed-staging.sh to read back.
  default_tenant_domain = coalesce(var.default_tenant_domain, local.publisher_fqdn)
}

module "compose_stack" {
  source = "../../modules/compose-stack"

  exchange_hostname = local.exchange_fqdn
  broker_hostname   = local.broker_fqdn
  identity_hostname = local.identity_fqdn
  zitadel_hostname  = local.zitadel_fqdn
  origin_hostname   = local.origin_fqdn

  exchange_image  = local.exchange_image
  broker_image    = local.broker_image
  identity_image  = local.identity_image
  publisher_image = local.publisher_image

  registry_server   = var.registry_username == null ? null : var.image_registry
  registry_username = var.registry_username
  registry_password = var.registry_password

  billing_adapter = var.billing_adapter
  acme_email      = var.acme_email
  acme_staging    = var.acme_staging
  exa_api_key     = var.exa_api_key

  default_tenant_domain = local.default_tenant_domain

  ed25519_private_pem     = file("${local.keys_dir}/ed25519-private.pem")
  rsa_private_pem         = local.rsa_private_pem
  broker_relay_key_json   = file("${local.keys_dir}/broker-relay-key.json")
  broker_identity_key_pem = file("${local.keys_dir}/broker-identity-key.pem")

  # PUBLIC key directories for the smoke identities (gen-staging-keys.sh
  # derives them from the local keypairs — the private halves never leave the
  # operator's machine). Caddy serves each at its identity's hostname, which is
  # how the Exchange and Broker verify the smoke and ingest signatures.
  static_wba_directories = {
    (local.smoke_agent_fqdn)         = file("${local.keys_dir}/smoke-agent-wba.json")
    (local.catalog_contributor_fqdn) = file("${local.keys_dir}/catalog-contributor-wba.json")
  }
}

# Renders the worker's publisher-manifest env values (EXCHANGES_JSON,
# CATALOG_CONTRIBUTORS_JSON) — the one Terraform home of that JSON shape,
# shared with the Lambda@Edge config rendering in stacks/demo-aws.
module "manifest" {
  source = "../../modules/publisher-manifest"

  exchange_fqdn     = local.exchange_fqdn
  resource_owner_id = var.resource_owner_id
  # The contributor id IS the hostname its key directory is served at (the
  # smoke identity hostname derived above) — there is no separate id variable.
  catalog_contributor_id = local.catalog_contributor_fqdn
}

module "vm" {
  source = "../../modules/aws-vm"

  name_prefix      = var.name_prefix
  instance_type    = var.instance_type
  ssh_public_key   = var.ssh_public_key
  ssh_ingress_cidr = var.ssh_ingress_cidr
  user_data        = module.compose_stack.user_data
}

module "dns" {
  source = "../../modules/cloudflare-dns"

  zone_id = var.cloudflare_zone_id
  a_records = {
    (var.exchange_subdomain) = module.vm.public_ip
    (var.broker_subdomain)   = module.vm.public_ip
    (var.identity_subdomain) = module.vm.public_ip
    (var.zitadel_subdomain)  = module.vm.public_ip
    (var.origin_subdomain)   = module.vm.public_ip
    # The smoke identities' key directory hostnames — Caddy serves each
    # identity's public JWK Set there (static_wba_directories above).
    (var.smoke_agent_subdomain)         = module.vm.public_ip
    (var.catalog_contributor_subdomain) = module.vm.public_ip
    # Agent Web Bot Auth directories: one hostname per agent, created by a
    # developer signing up rather than by Terraform, so the record has to be a
    # wildcard. Caddy mints each subdomain's certificate on demand.
    ("*.${var.identity_subdomain}") = module.vm.public_ip
  }
}

# The module's other optional standalone-publisher inputs (ramp_verify_keys,
# rsl_body, acme_tokens_json, wba_keys_json, wba_revocation_url) are omitted
# on purpose, not by oversight: staging's Exchange serves agent keys over
# exchange_wba_url, so inline key material is unnecessary. stacks/edge exposes
# all of them because it is the generic surface a publisher configures alone.
# ramp_enforce_binding IS exposed (var.ramp_enforce_binding) so the backend
# can be smoked alone with binding off; null keeps the module default — enforce
# agent-key proof-of-possession, the production posture. smoke.sh reads the
# posture back from the stack's ramp_enforce_binding output, so the bare-fetch
# check asserts whichever outcome this deployment actually promises (403
# enforcing, 200 with binding off).
module "edge" {
  count  = var.deploy_edge ? 1 : 0
  source = "../../modules/cloudflare-edge"

  account_id         = var.cloudflare_account_id
  zone_id            = var.cloudflare_zone_id
  script_name        = "${var.name_prefix}-edge"
  worker_bundle_path = local.worker_bundle_path

  route_patterns  = ["${local.publisher_fqdn}/*"]
  worker_hostname = local.publisher_fqdn

  exchange_url     = "https://${local.exchange_fqdn}"
  exchange_wba_url = "https://${local.exchange_fqdn}/.well-known/http-message-signatures-directory"
  provider_domain  = local.publisher_fqdn
  exchanges_json   = module.manifest.exchanges_json

  origin_url = "https://${local.origin_fqdn}"
  # Rendered by the manifest module — the one Terraform home of this JSON
  # shape, shared with the Lambda@Edge config rendering in stacks/demo-aws.
  catalog_contributors_json = module.manifest.catalog_contributors_json

  ramp_enforce_binding = var.ramp_enforce_binding

  create_waf_skip_rule = var.create_waf_skip_rule
  waf_skip_expression  = var.create_waf_skip_rule ? "(http.host eq \"${local.publisher_fqdn}\")" : null
}
